# Generated by Django 5.0.3 on 2026-05-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '06. Rotina Automática',
                'verbose_name_plural': '06. Rotinas Automáticas',
            },
        ),
        migrations.CreateModel(
            name='ConnectedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '09. Usuário Conectado',
                'verbose_name_plural': '09. Usuários Conectados',
            },
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '02. Configuração de E-mail',
                'verbose_name_plural': '02. Configurações de E-mail',
            },
        ),
        migrations.CreateModel(
            name='IntegrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '08. Token de Integração',
                'verbose_name_plural': '08. Tokens de Integração',
            },
        ),
        migrations.CreateModel(
            name='SMSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '03. Configuração SMS',
                'verbose_name_plural': '03. Configurações SMS',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '05. Log do Sistema',
                'verbose_name_plural': '05. Logs do Sistema',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '01. Chamado Técnico',
                'verbose_name_plural': '01. Chamados Técnicos',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '07. Treinamento',
                'verbose_name_plural': '07. Treinamentos',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '04. Configuração WhatsApp',
                'verbose_name_plural': '04. Configurações WhatsApp',
            },
        ),
    ]
