# Generated by Django 5.0.3 on 2026-05-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfiguration',
        ),
        migrations.DeleteModel(
            name='SMSConfiguration',
        ),
        migrations.DeleteModel(
            name='WhatsAppSettings',
        ),
        migrations.AlterModelOptions(
            name='automatedroutine',
            options={'verbose_name': '03. Rotina Automática', 'verbose_name_plural': '03. Rotinas Automáticas'},
        ),
        migrations.AlterModelOptions(
            name='connecteduser',
            options={'verbose_name': '06. Usuário Conectado', 'verbose_name_plural': '06. Usuários Conectados'},
        ),
        migrations.AlterModelOptions(
            name='integrationtoken',
            options={'verbose_name': '05. Token de Integração', 'verbose_name_plural': '05. Tokens de Integração'},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'verbose_name': '02. Log do Sistema', 'verbose_name_plural': '02. Logs do Sistema'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': '04. Treinamento', 'verbose_name_plural': '04. Treinamentos'},
        ),
    ]
