# Generated by Django 5.0.3 on 2026-04-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0012_alter_collaborators_options_types_collaborators_and_more'),
        ('personalities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssector',
            options={'ordering': ['description'], 'verbose_name': '1. Ramo de Atividade', 'verbose_name_plural': '1. Ramos de Atividade'},
        ),
        migrations.AlterUniqueTogether(
            name='businesssector',
            unique_together={('description',)},
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Entidade')),
                ('kind', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo')),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True, verbose_name='CPF/CNPJ')),
                ('rg_ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG/IE')),
                ('municipal_registration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal')),
                ('trade_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Fantasia')),
                ('date_of_birth_opening', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento/Abertura')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominium.addresses', verbose_name='Endereço')),
                ('business_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalities.businesssector', verbose_name='Ramo de Atividade')),
            ],
            options={
                'verbose_name': '2. Entidade',
                'verbose_name_plural': '2. Entidades',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
    ]
