# Generated by Django 5.0.3 on 2026-04-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalities', '0002_alter_businesssector_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['business_sector', 'name', 'cpf_cnpj'], 'verbose_name': '2. Entidade', 'verbose_name_plural': '2. Entidades'},
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('business_sector', 'cpf_cnpj')},
        ),
    ]
