# Generated by Django 5.0.3 on 2026-05-05 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
        ('personalities', '0003_alter_entity_options_alter_entity_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.addresses', verbose_name='Endereço'),
        ),
    ]
