# Generated by Django 5.0.3 on 2026-05-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalities', '0004_alter_entity_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
