# Generated by Django 5.0.3 on 2026-05-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalities', '0005_alter_entity_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='death',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='Óbito'),
        ),
        migrations.AddField(
            model_name='entity',
            name='regular',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='CPF Regular'),
        ),
        migrations.AddField(
            model_name='entity',
            name='situation',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Situação Receita Federal'),
        ),
    ]
