# Generated by Django 5.0.3 on 2026-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalities', '0007_entity_api_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='retorno_api',
            field=models.TextField(blank=True, null=True, verbose_name='Retorno da API'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(default='pendente', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='phone',
            field=models.CharField(default='(19) 9876-0900', max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='rg_ie',
            field=models.CharField(default='isento', max_length=20, verbose_name='RG/IE'),
            preserve_default=False,
        ),
    ]
