# Generated by Django 5.0.3 on 2026-07-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalities', '0010_alter_businesssector_options_alter_entity_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='businesssector',
            table='personalities_businesssector',
        ),
        migrations.AlterModelTable(
            name='entity',
            table='personalities_entity',
        ),
    ]
