# Generated by Django 5.0.3 on 2026-03-08 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Estado')),
                ('abbreviation', models.CharField(max_length=2, unique=True, verbose_name='UF')),
            ],
            options={
                'verbose_name': '2. Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ['country', 'state', 'city', 'street', 'number', 'complement'], 'verbose_name': '3. Endereço', 'verbose_name_plural': '2. Endereços'},
        ),
        migrations.AlterModelOptions(
            name='condominium',
            options={'ordering': ['name', 'code', 'cnpj'], 'verbose_name': '4. Condomínio', 'verbose_name_plural': '3. Condomínios'},
        ),
        migrations.AlterModelOptions(
            name='typescondominium',
            options={'ordering': ['name'], 'verbose_name': '1. Tipo de Condomínio', 'verbose_name_plural': '1. Tipos de Condomínios'},
        ),
        migrations.AlterField(
            model_name='addresses',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='condominium.states', verbose_name='UF'),
        ),
    ]
