# Generated by Django 5.0.3 on 2026-03-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0005_alter_addresses_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='complement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complemento'),
        ),
    ]
