# Generated by Django 5.0.3 on 2026-04-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0010_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
