# Generated by Django 5.0.3 on 2026-04-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0016_alter_addresses_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ['country', 'state', 'city', 'street', 'complement', 'is_active', 'created_at'], 'verbose_name': '4. Endereço', 'verbose_name_plural': '4. Endereços'},
        ),
        migrations.AlterUniqueTogether(
            name='addresses',
            unique_together={('street', 'neighborhood', 'city', 'state', 'zip_code')},
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='number',
        ),
    ]
