# Generated by Django 5.0.3 on 2026-04-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0018_alter_addresses_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='number',
            field=models.IntegerField(max_length=10, verbose_name='Número'),
        ),
    ]
