# Generated by Django 5.0.3 on 2026-04-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0020_auto_20260418_0700'),
    ]

    operations = [
    ]
