# Generated by Django 5.0.3 on 2026-05-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0031_collaborators_death_collaborators_regular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='api_status',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='Status da API'),
        ),
    ]
