# Generated by Django 5.0.3 on 2026-04-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0006_alter_addresses_complement'),
        ('residents', '0003_rename_structure_condominiumunit_tower'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='condominiumunit',
            name='unique_unit_per_structure',
        ),
        migrations.AddConstraint(
            model_name='condominiumunit',
            constraint=models.UniqueConstraint(fields=('tower', 'unit_number'), name='unique_unit_per_tower'),
        ),
    ]
