# Generated by Django 5.0.3 on 2026-04-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_remove_condominiumunit_unique_unit_per_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominiumunit',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de banheiros'),
        ),
        migrations.AlterField(
            model_name='condominiumunit',
            name='bedrooms',
            field=models.PositiveIntegerField(default=2, verbose_name='Número de quartos'),
        ),
        migrations.AlterField(
            model_name='condominiumunit',
            name='garage_spaces',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de vagas de garagem'),
        ),
        migrations.AlterField(
            model_name='condominiumunit',
            name='unit_type',
            field=models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('commercial', 'Comercial'), ('office', 'Sala Comercial'), ('store', 'Loja')], default='apartment', max_length=20, verbose_name='Tipo'),
        ),
    ]
