# Generated by Django 5.0.3 on 2026-04-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0011_alter_animal_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='location',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='reported_by',
        ),
    ]
