# Generated by Django 5.0.3 on 2026-04-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0026_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('personal', 'Documentos Pessoais'), ('cadastral', 'Cadastrais'), ('contracts', 'Contratos'), ('receipts', 'Comprovantes'), ('TAX', 'Documentos Fiscais'), ('vehicle_data', 'Dados de veículos'), ('animal_data', 'Dados de animais'), ('other', 'Outros')], default='personal', max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
