# Generated by Django 5.0.3 on 2026-04-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0029_alter_vehicle_license_plate_alter_vehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
    ]
