# Generated by Django 5.0.3 on 2026-05-05 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
        ('residents', '0031_alter_emergency_condo_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateagency',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='parameters.addresses', verbose_name='Endereço'),
        ),
    ]
