# Generated by Django 5.0.3 on 2026-05-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0032_alter_realestateagency_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='residents/photos/', verbose_name='Foto'),
        ),
    ]
