# Generated by Django 5.0.3 on 2026-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0034_vehicle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='residents/animals/', verbose_name='Foto'),
        ),
    ]
