# Generated by Django 5.0.3 on 2026-05-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0036_visitor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateagency',
            name='trade_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia'),
        ),
    ]
