# Generated by Django 5.0.3 on 2026-05-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0044_remove_resident_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='residents/certidoes/', verbose_name='Arquivo da certidão'),
        ),
        migrations.AddField(
            model_name='resident',
            name='certificate_presentation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de apresentação da certidão'),
        ),
        migrations.AddField(
            model_name='resident',
            name='certificate_validity',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da certidão'),
        ),
        migrations.AddField(
            model_name='resident',
            name='observations_certificate',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da certidão'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='residents/certidoes/', verbose_name='Arquivo da certidão'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='certificate_presentation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de apresentação da certidão'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='certificate_validity',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da certidão'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='observations_certificate',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da certidão'),
        ),
    ]
