services:
  web:
    build: .
    container_name: django_project_web
    command: /scripts/command.sh
    volumes:
      - ./app:/app
      - ./scripts:/scripts
      - ./data/web/static:/app/staticfiles
      - ./data/web/media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - db
    networks:
      - django-network

  db:
    image: postgres:16
    container_name: django_project_db
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./dotenv_files/.env
    networks:
      - django-network

networks:
  django-network:
    driver: bridge
