# Generated by Django 5.0.3 on 2026-05-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_add_state_id_to_addresses'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addresses',
            table=None,
        ),
        migrations.AlterModelTable(
            name='states',
            table=None,
        ),
        migrations.AlterModelTable(
            name='structioncondominium',
            table=None,
        ),
        migrations.AlterModelTable(
            name='typescondominium',
            table=None,
        ),
    ]
