# Generated by Django 5.0.3 on 2026-05-18 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_typesvisitorrestrictions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ['country', 'state', 'city', 'street', 'number', 'complement', 'is_active', 'created_at'], 'verbose_name': '04. Endereço', 'verbose_name_plural': '04. Endereços'},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'ordering': ['abbreviation', 'name', 'region'], 'verbose_name': '03. Estado', 'verbose_name_plural': '03. Estados'},
        ),
        migrations.AlterModelOptions(
            name='structioncondominium',
            options={'ordering': ['name', 'is_active', 'created_at'], 'verbose_name': '02. Estrutura do Condomínio', 'verbose_name_plural': '02. Estruturas dos Condomínios'},
        ),
        migrations.AlterModelOptions(
            name='typescondominium',
            options={'ordering': ['name', 'is_active', 'created_at'], 'verbose_name': '01. Tipo de Condomínio', 'verbose_name_plural': '01. Tipos de Condomínios'},
        ),
        migrations.AlterModelOptions(
            name='typesvisitorrestrictions',
            options={'ordering': ['description'], 'verbose_name': '05. Tipo de Restrição/Visitante', 'verbose_name_plural': '05. Tipos de Restrição/Visitantes'},
        ),
    ]
