# Generated by Django 5.0.3 on 2026-09-23 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominium', '0038_alter_collaborator_name_alter_condominium_is_active_and_more'),
        ('parameters', '0031_topicoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '08. Malote',
                'verbose_name_plural': '08. Malotes',
            },
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '06. Correspondência',
                'verbose_name_plural': '06. Correspondências',
            },
        ),
        migrations.CreateModel(
            name='ElectronicTimeClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '09. Ponto Eletrônico',
                'verbose_name_plural': '09. Pontos Eletrônicos',
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '07. Ocorrência',
                'verbose_name_plural': '07. Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '04. Encomenda',
                'verbose_name_plural': '04. Encomendas',
            },
        ),
        migrations.CreateModel(
            name='ServiceTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '02. Passagem de Serviço',
                'verbose_name_plural': '02. Passagens de Serviços',
            },
        ),
        migrations.CreateModel(
            name='UsefulPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '03. Telefone Útil',
                'verbose_name_plural': '03. Telefones Úteis',
            },
        ),
        migrations.CreateModel(
            name='VisitorsRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '05. Reg. Visitante',
                'verbose_name_plural': '05. Reg. Visitantes',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(help_text='Data inicial do plantão', verbose_name='Data Inicial')),
                ('endDate', models.DateField(help_text='Data final do plantão', verbose_name='Data Final')),
                ('title', models.CharField(blank=True, help_text='Título do plantão', max_length=255, verbose_name='Título')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o plantão está ativo', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('collaborator', models.ForeignKey(help_text='Colaborador do plantão', on_delete=django.db.models.deletion.CASCADE, to='condominium.collaborator', verbose_name='Colaborador')),
                ('condominium', models.ForeignKey(help_text='Condomínio associado ao plantão', on_delete=django.db.models.deletion.CASCADE, to='condominium.condominium', verbose_name='Condomínio')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Usuário que criou o plantão', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('status', models.ForeignKey(help_text='Status do plantão', on_delete=django.db.models.deletion.CASCADE, to='parameters.chartofaccountsstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': '01. Plantão',
                'verbose_name_plural': '01. Plantões',
            },
        ),
        migrations.CreateModel(
            name='ShiftScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Descrição da escala', max_length=255, verbose_name='Descrição')),
                ('shiftDate', models.DateField(help_text='Data da escala', verbose_name='Data da Escala')),
                ('startTime', models.TimeField(help_text='Hora inicial da escala', verbose_name='Hora Inicial')),
                ('endTime', models.TimeField(help_text='Hora final da escala', verbose_name='Hora Final')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a escala está ativa', verbose_name='Ativo')),
                ('shift', models.ForeignKey(help_text='Plantão ao qual esta escala pertence', on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='gatehouse.shift', verbose_name='Plantão')),
            ],
            options={
                'verbose_name': '01. Escala',
                'verbose_name_plural': '01. Escalas',
            },
        ),
    ]
