# Generated by Django 5.0.3 on 2026-09-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0038_alter_collaborator_name_alter_condominium_is_active_and_more'),
        ('gatehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominium.collaborator', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominium.condominium', verbose_name='Condomínio'),
        ),
    ]
