# Generated by Django 5.0.3 on 2026-09-24 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0002_alter_shift_collaborator_alter_shift_condominium'),
        ('parameters', '0031_topicoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.ForeignKey(help_text='Status do plantão', on_delete=django.db.models.deletion.CASCADE, to='parameters.assemblystatus', verbose_name='Status'),
        ),
    ]
