# Generated by Django 5.0.3 on 2026-09-24 22:07

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0038_alter_collaborator_name_alter_condominium_is_active_and_more'),
        ('gatehouse', '0003_alter_shift_status'),
        ('parameters', '0031_topicoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTransitionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemObj', models.CharField(max_length=255, verbose_name='Item')),
                ('amountObj', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('shiftDate', models.DateField(verbose_name='Data do turno')),
                ('startTime', models.TimeField(verbose_name='Horário inicial')),
                ('endTime', models.TimeField(verbose_name='Horário final')),
            ],
            options={
                'verbose_name': '02. Objeto da Passagem de Serviço',
                'verbose_name_plural': '02. Objetos da Passagem de Serviço',
                'ordering': ['shiftDate', 'startTime', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicetransition',
            options={'ordering': ['-releaseDate', '-id'], 'verbose_name': '02. Passagem de Serviço', 'verbose_name_plural': '02. Passagens de Serviços'},
        ),
        migrations.AddField(
            model_name='servicetransition',
            name='collaboratorEnd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_transitions_end', to='condominium.collaborator', verbose_name='Colaborador de saída'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetransition',
            name='collaboratorStart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_transitions_start', to='condominium.collaborator', verbose_name='Colaborador de entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetransition',
            name='condominium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_transitions', to='condominium.condominium', verbose_name='Condomínio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetransition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetransition',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='servicetransition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='servicetransition',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='servicetransition',
            name='releaseDate',
            field=models.DateField(default=datetime.date(2026, 1, 1), verbose_name='Data de lançamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetransition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddIndex(
            model_name='servicetransition',
            index=models.Index(fields=['releaseDate'], name='idx_svctrans_release_date'),
        ),
        migrations.AddConstraint(
            model_name='servicetransition',
            constraint=models.UniqueConstraint(fields=('condominium', 'collaboratorEnd', 'collaboratorStart', 'releaseDate'), name='uniq_svctrans_cond_end_date'),
        ),
        migrations.AddField(
            model_name='servicetransitionobject',
            name='categoryObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_transition_objects', to='parameters.assemblystatus', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='servicetransitionobject',
            name='service_transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gatehouse.servicetransition', verbose_name='Passagem de serviço'),
        ),
    ]
