# Generated by Django 5.0.3 on 2026-09-26 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0004_servicetransitionobject_and_more'),
        ('parameters', '0032_conciergeservicecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetransitionobject',
            name='categoryObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='parameters.conciergeservicecategory', verbose_name='Categoria'),
        ),
    ]
