# Generated by Django 5.0.3 on 2026-05-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0004_electronictimeclock_alter_bag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bag',
            options={'verbose_name': '08. Malote', 'verbose_name_plural': '08. Malotes'},
        ),
        migrations.AlterModelOptions(
            name='correspondence',
            options={'verbose_name': '06. Correspondência', 'verbose_name_plural': '06. Correspondências'},
        ),
        migrations.AlterModelOptions(
            name='electronictimeclock',
            options={'verbose_name': '09. Ponto Eletrônico', 'verbose_name_plural': '09. Pontos Eletrônicos'},
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'verbose_name': '07. Ocorrência', 'verbose_name_plural': '07. Ocorrências'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '04. Encomenda', 'verbose_name_plural': '04. Encomendas'},
        ),
        migrations.AlterModelOptions(
            name='servicetransition',
            options={'verbose_name': '02. Passagem de Serviço', 'verbose_name_plural': '02. Passagens de Serviços'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': '01. Plantão', 'verbose_name_plural': '01. Plantões'},
        ),
        migrations.AlterModelOptions(
            name='usefulphonenumber',
            options={'verbose_name': '03. Telefone Útil', 'verbose_name_plural': '03. Telefones Úteis'},
        ),
        migrations.AlterModelOptions(
            name='visitorsregister',
            options={'verbose_name': '05. Reg. Visitante', 'verbose_name_plural': '05. Reg. Visitantes'},
        ),
    ]
