# Generated by Django 5.0.3 on 2026-09-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0005_alter_servicetransitionobject_categoryobj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetransitionobject',
            name='description',
        ),
    ]
