# Generated by Django 5.0.3 on 2026-09-26 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0006_remove_servicetransitionobject_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetransitionobject',
            options={'ordering': ['shiftDate', 'id'], 'verbose_name': '02. Objeto da Passagem de Serviço', 'verbose_name_plural': '02. Objetos da Passagem de Serviço'},
        ),
        migrations.RemoveField(
            model_name='servicetransitionobject',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='servicetransitionobject',
            name='startTime',
        ),
        migrations.AlterField(
            model_name='servicetransitionobject',
            name='shiftDate',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do turno'),
        ),
    ]
