# Generated by Django 5.0.3 on 2026-10-03 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0038_alter_collaborator_name_alter_condominium_is_active_and_more'),
        ('gatehouse', '0007_alter_servicetransitionobject_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a categoria está ativa', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Telefone',
                'verbose_name_plural': 'Categorias de Telefone',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='usefulphonenumber',
            options={'ordering': ['name', 'id'], 'verbose_name': '03. Telefone Útil', 'verbose_name_plural': '03. Telefones Úteis'},
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='condominium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condominium.condominium', verbose_name='Condomínio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Data e hora da criação', verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o telefone está ativo', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='phone1',
            field=models.CharField(default='', help_text='Digite no seguinte formato: (99) 99999-9999', max_length=25, verbose_name='Telefone 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='phone2',
            field=models.CharField(blank=True, help_text='Digite no seguinte formato: (99) 99999-9999', max_length=25, verbose_name='Telefone 2'),
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='phone3',
            field=models.CharField(blank=True, help_text='Digite no seguinte formato: (99) 99999-9999', max_length=25, verbose_name='Telefone 3'),
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='phone4',
            field=models.CharField(blank=True, help_text='Digite no seguinte formato: (99) 99999-9999', max_length=25, verbose_name='Telefone 4'),
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='phone5',
            field=models.CharField(blank=True, help_text='Digite no seguinte formato: (99) 99999-9999', max_length=25, verbose_name='Telefone 5'),
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='releaseDate',
            field=models.DateField(blank=True, help_text='Data de lançamento (obrigatória no formulário)', null=True, verbose_name='Data de lançamento'),
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='usefulphonenumber',
            name='categoryPhone',
            field=models.ForeignKey(blank=True, help_text='Categoria do telefone (obrigatória no formulário)', null=True, on_delete=django.db.models.deletion.CASCADE, to='gatehouse.categoryphone', verbose_name='Categoria do telefone'),
        ),
        migrations.AddConstraint(
            model_name='usefulphonenumber',
            constraint=models.UniqueConstraint(fields=('condominium', 'categoryPhone', 'name', 'releaseDate'), name='uniq_uphone_cond_cat_name_date'),
        ),
    ]
