# Generated by Django 5.0.3 on 2026-10-03 14:25

import django.db.models.deletion
from django.db import migrations, models


def copy_categoryphone_forward(apps, schema_editor):
    """Copia as categorias existentes para o novo app preservando os pks."""
    OldCategoryPhone = apps.get_model("gatehouse", "CategoryPhone")
    NewCategoryPhone = apps.get_model("parameters", "CategoryPhone")
    for row in OldCategoryPhone.objects.all():
        NewCategoryPhone.objects.update_or_create(
            pk=row.pk,
            defaults={"name": row.name, "is_active": row.is_active},
        )


def copy_categoryphone_backward(apps, schema_editor):
    """Devolve as categorias para o app antigo (reversao da migracao)."""
    OldCategoryPhone = apps.get_model("gatehouse", "CategoryPhone")
    NewCategoryPhone = apps.get_model("parameters", "CategoryPhone")
    for row in NewCategoryPhone.objects.all():
        OldCategoryPhone.objects.update_or_create(
            pk=row.pk,
            defaults={"name": row.name, "is_active": row.is_active},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0008_categoryphone_alter_usefulphonenumber_options_and_more'),
        ('parameters', '0033_categoryphone'),
    ]

    operations = [
        migrations.RunPython(
            copy_categoryphone_forward,
            copy_categoryphone_backward,
        ),
        migrations.AlterField(
            model_name='usefulphonenumber',
            name='categoryPhone',
            field=models.ForeignKey(blank=True, help_text='Categoria do telefone (obrigatória no formulário)', null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.categoryphone', verbose_name='Categoria do telefone'),
        ),
        migrations.DeleteModel(
            name='CategoryPhone',
        ),
    ]
