# Generated by Django 5.0.3 on 2026-10-05 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0009_alter_usefulphonenumber_categoryphone_and_more'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-releaseDate', '-id'], 'verbose_name': '04. Encomenda', 'verbose_name_plural': '04. Encomendas'},
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Data e hora da criação', verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='order',
            name='documentNumber',
            field=models.CharField(blank=True, help_text='Conteúdo numérico ou alfanumérico, sem máscara (opcional)', max_length=255, null=True, verbose_name='Número do documento'),
        ),
        migrations.AddField(
            model_name='order',
            name='fileImage',
            field=models.FileField(default='', help_text='Imagem ou PDF de até 10 MB (.jpg, .jpeg, .png, .pdf)', upload_to='gatehouse/orders/', verbose_name='Arquivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se a encomenda está ativa', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='order',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='order',
            name='releaseDate',
            field=models.DateField(blank=True, help_text='Data de chegada da encomenda (preenchida pelo servidor na criação)', null=True, verbose_name='Data de lançamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='residents.condominiumunit', verbose_name='Unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('unit', 'releaseDate', 'documentNumber'), name='uniq_order_unit_date_doc'),
        ),
    ]
