# Generated by Django 5.0.3 on 2026-10-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0010_alter_order_options_order_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Imagem de até 10 MB (.jpg, .jpeg, .png)', upload_to='gatehouse/orders/photos/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da anexação', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Usuário que anexou a foto', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gatehouse.order', verbose_name='Encomenda')),
            ],
            options={
                'verbose_name': 'Foto de Encomenda',
                'verbose_name_plural': 'Fotos de Encomenda',
                'ordering': ['id'],
            },
        ),
    ]
