# Generated by Django 5.0.3 on 2026-10-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0011_orderphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fileImage',
            field=models.FileField(blank=True, help_text='Imagem ou PDF de até 10 MB (.jpg, .jpeg, .png, .pdf). Opcional quando houver ao menos uma foto anexada', upload_to='gatehouse/orders/', verbose_name='Arquivo'),
        ),
    ]
