# Generated by Django 5.0.3 on 2026-10-07 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0012_alter_order_fileimage'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorsregister',
            options={'ordering': ['-visitDate', '-id'], 'verbose_name': '05. Reg. Visitante', 'verbose_name_plural': '05. Reg. Visitantes'},
        ),
        migrations.AddField(
            model_name='visitorsregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorsregister',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuário da última gravação do registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='visitorsregister',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='visitorsregister',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='visitorsregister',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='visitorsregister',
            name='visitDate',
            field=models.DateField(blank=True, help_text='Data da visita (obrigatória no formulário; preenchida pelo servidor na criação)', null=True, verbose_name='Data da visita'),
        ),
        migrations.AddField(
            model_name='visitorsregister',
            name='visitor',
            field=models.ForeignKey(default=1, help_text='Visitante responsável pela visita', on_delete=django.db.models.deletion.CASCADE, related_name='visit_registers', to='residents.visitor', verbose_name='Visitante'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='visitorsregister',
            constraint=models.UniqueConstraint(fields=('visitor', 'visitDate'), name='uniq_visitreg_visitor_date'),
        ),
    ]
