# Generated by Django 5.0.3 on 2026-10-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0013_alter_visitorsregister_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correspondence',
        ),
    ]
