# Generated by Django 5.0.3 on 2026-10-08 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0038_alter_collaborator_name_alter_condominium_is_active_and_more'),
        ('gatehouse', '0014_delete_correspondence'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['-releaseDate', '-id'], 'verbose_name': '07. Ocorrência', 'verbose_name_plural': '07. Ocorrências'},
        ),
        migrations.AddField(
            model_name='occurrence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occurrence',
            name='created_user',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuário da última gravação do registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Colaboradores participantes (opcional)', related_name='occurrences', to='condominium.collaborator', verbose_name='Participantes'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='releaseDate',
            field=models.DateTimeField(blank=True, help_text='Data e hora da ocorrência (obrigatórias no formulário; preenchidas pelo servidor na criação)', null=True, verbose_name='Data/hora da ocorrência'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='subject',
            field=models.CharField(default='', help_text='Assunto da ocorrência (até 255 caracteres)', max_length=255, verbose_name='Assunto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occurrence',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unidade da ocorrência (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='residents.condominiumunit', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.UniqueConstraint(fields=('unit', 'releaseDate', 'subject'), name='uniq_occurrence_unit_date_subject'),
        ),
    ]
