# Generated by Django 5.0.3 on 2026-05-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_maintenancereservations_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '4. Reforma',
                'verbose_name_plural': '4. Reformas',
            },
        ),
    ]
