# Generated by Django 5.0.3 on 2026-05-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancereservations',
            options={'verbose_name': '2. Manutenção', 'verbose_name_plural': '2. Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='movereservations',
            options={'verbose_name': '3. Mudança', 'verbose_name_plural': '3. Mudanças'},
        ),
        migrations.AlterModelOptions(
            name='rentals',
            options={'verbose_name': '1. Locação', 'verbose_name_plural': '1. Locações'},
        ),
        migrations.RemoveField(
            model_name='maintenancereservations',
            name='active',
        ),
        migrations.RemoveField(
            model_name='movereservations',
            name='active',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='active',
        ),
    ]
