# Generated by Django 5.0.3 on 2026-05-18 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reforms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancereservations',
            options={'verbose_name': '02. Manutenção', 'verbose_name_plural': '02. Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='movereservations',
            options={'verbose_name': '03. Mudança', 'verbose_name_plural': '03. Mudanças'},
        ),
        migrations.AlterModelOptions(
            name='reforms',
            options={'verbose_name': '04. Reforma', 'verbose_name_plural': '04. Reformas'},
        ),
        migrations.AlterModelOptions(
            name='rentals',
            options={'verbose_name': '01. Locação', 'verbose_name_plural': '01. Locações'},
        ),
    ]
