# Generated by Django 5.0.3 on 2026-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '04. Histórico de E-mail',
                'verbose_name_plural': '04. Históricos de E-mails',
            },
        ),
        migrations.CreateModel(
            name='ShippingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '03. Fila de Envio',
                'verbose_name_plural': '03. Filas de Envio',
            },
        ),
        migrations.CreateModel(
            name='SMTP_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '01. Configuração SMTP',
                'verbose_name_plural': '01. Configurações SMTP',
            },
        ),
        migrations.CreateModel(
            name='UsageProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '02. Perfil de Uso',
                'verbose_name_plural': '02. Perfis de Uso',
            },
        ),
    ]
