# Generated by Django 5.0.3 on 2026-05-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0002_alter_emailhistory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypesProvider',
        ),
        migrations.AlterModelOptions(
            name='emailhistory',
            options={'verbose_name': '04. Histórico de E-mail', 'verbose_name_plural': '04. Históricos de E-mails'},
        ),
        migrations.AlterModelOptions(
            name='shippingqueue',
            options={'verbose_name': '03. Fila de Envio', 'verbose_name_plural': '03. Filas de Envio'},
        ),
        migrations.AlterModelOptions(
            name='smtp_settings',
            options={'verbose_name': '01. Configuração SMTP', 'verbose_name_plural': '01. Configurações SMTP'},
        ),
        migrations.AlterModelOptions(
            name='usageprofiles',
            options={'verbose_name': '02. Perfil de Uso', 'verbose_name_plural': '02. Perfis de Uso'},
        ),
    ]
