# Generated by Django 5.0.3 on 2026-05-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0003_delete_typesprovider_alter_emailhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailhistory',
            options={'verbose_name': '06. Histórico de E-mail', 'verbose_name_plural': '06. Históricos de E-mails'},
        ),
        migrations.AlterModelOptions(
            name='shippingqueue',
            options={'verbose_name': '05. Fila de Envio', 'verbose_name_plural': '05. Filas de Envio'},
        ),
        migrations.AlterModelOptions(
            name='smtp_settings',
            options={'verbose_name': '03. Configuração SMTP', 'verbose_name_plural': '03. Configurações SMTP'},
        ),
        migrations.AlterModelOptions(
            name='usageprofiles',
            options={'verbose_name': '04. Perfil de Uso', 'verbose_name_plural': '04. Perfis de Uso'},
        ),
        migrations.CreateModel(
            name='TypesProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('provider', models.CharField(max_length=255, verbose_name='Provedor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': '01. Tipo de Provedor',
                'verbose_name_plural': '01. Tipos de Provedores',
                'unique_together': {('description', 'provider')},
            },
        ),
    ]
