# Generated by Django 5.0.3 on 2026-05-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0004_alter_emailhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='typesprovider',
            unique_together={('provider',)},
        ),
        migrations.CreateModel(
            name='ConnectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('status', models.CharField(max_length=255, verbose_name='Status de Conexão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': '02. Status de Conexão',
                'verbose_name_plural': '02. Status de Conexão',
                'unique_together': {('status',)},
            },
        ),
        migrations.RemoveField(
            model_name='typesprovider',
            name='description',
        ),
    ]
