# Generated by Django 5.0.3 on 2026-05-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0005_alter_typesprovider_unique_together_connectionstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionstatus',
            name='description',
        ),
    ]
