# Generated by Django 5.0.3 on 2026-05-22 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0006_remove_connectionstatus_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailhistory',
            options={'verbose_name': '07. Histórico de E-mail', 'verbose_name_plural': '07. Históricos de E-mails'},
        ),
        migrations.AlterModelOptions(
            name='shippingqueue',
            options={'verbose_name': '06. Fila de Envio', 'verbose_name_plural': '06. Filas de Envio'},
        ),
        migrations.AlterModelOptions(
            name='smtp_settings',
            options={'verbose_name': '04. Configuração SMTP', 'verbose_name_plural': '04. Configurações SMTP'},
        ),
        migrations.AlterModelOptions(
            name='usageprofiles',
            options={'verbose_name': '05. Perfil de Uso', 'verbose_name_plural': '05. Perfis de Uso'},
        ),
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Descrição')),
                ('provider_code', models.CharField(max_length=50, unique=True, verbose_name='Código do Provedor')),
                ('smtp_host', models.CharField(max_length=255, verbose_name='Host SMTP')),
                ('smtp_port', models.IntegerField(verbose_name='Porta SMTP')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Utilizar TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Utilizar SSL')),
                ('smtp_authentication', models.BooleanField(default=True, verbose_name='Requer Autenticação SMTP')),
                ('api_supported', models.BooleanField(default=False, verbose_name='Suporta API')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('api_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da API')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave da API')),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Segredo da API')),
                ('api_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão da API')),
                ('emails_per_hour', models.IntegerField(blank=True, null=True, verbose_name='Limite de E-mails por Hora')),
                ('emails_per_day', models.IntegerField(blank=True, null=True, verbose_name='Limite de E-mails por Dia')),
                ('max_recipients_per_email', models.IntegerField(blank=True, null=True, verbose_name='Máximo de Destinatários por E-mail')),
                ('test_email_address', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail para Testes')),
                ('last_connection_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Teste de Conexão')),
                ('connection_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_service.connectionstatus', verbose_name='Status de Conexão')),
                ('provider_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_service.typesprovider', verbose_name='Tipo de Provedor')),
            ],
            options={
                'verbose_name': '03. Provedor de E-mail',
                'verbose_name_plural': '03. Provedores de E-mail',
            },
        ),
    ]
