# Generated by Django 5.0.3 on 2026-05-23 15:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0007_alter_emailhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionstatus',
            name='description',
            field=models.CharField(default='Sem descrição', max_length=255, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Descrição')),
                ('provider_code', models.CharField(max_length=50, unique=True, verbose_name='Código do Provedor')),
                ('smtp_host', models.CharField(max_length=255, verbose_name='Host SMTP')),
                ('smtp_port', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Porta SMTP')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome de Usuário')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Utilizar TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Utilizar SSL')),
                ('smtp_authentication', models.BooleanField(default=True, verbose_name='Requer autenticação SMTP')),
                ('api_supported', models.BooleanField(default=False, verbose_name='Suporta API')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('api_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL API')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave API')),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Segredo API')),
                ('api_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão API')),
                ('emails_per_hour', models.IntegerField(blank=True, null=True, verbose_name='Limite por hora')),
                ('emails_per_day', models.IntegerField(blank=True, null=True, verbose_name='Limite por dia')),
                ('max_recipients_per_email', models.IntegerField(blank=True, null=True, verbose_name='Máximo destinatários')),
                ('test_email_address', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail para testes')),
                ('last_connection_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='Último teste')),
                ('connection_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smtp_configuration', to='email_service.connectionstatus', verbose_name='Status conexão')),
                ('provider_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_configuration', to='email_service.typesprovider', verbose_name='Tipo de Provedor')),
            ],
            options={
                'verbose_name': '04. Configuração SMTP',
                'verbose_name_plural': '04. Configurações SMTP',
                'ordering': ['description'],
                'unique_together': {('description', 'provider_code')},
            },
        ),
        migrations.DeleteModel(
            name='EmailProvider',
        ),
    ]
