# Generated by Django 5.0.3 on 2026-05-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0008_connectionstatus_description_smtpconfiguration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMTP_Settings',
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='api_secret',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Segredo API'),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='api_supported',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Suporta API'),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='smtp_authentication',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Requer autenticação SMTP'),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='use_ssl',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Utilizar SSL'),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='use_tls',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Utilizar TLS'),
        ),
    ]
