# Generated by Django 5.0.3 on 2026-05-26 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0009_delete_smtp_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usageprofiles',
            options={'ordering': ['purpose'], 'verbose_name': '05. Perfil de Uso', 'verbose_name_plural': '05. Perfis de Uso'},
        ),
        migrations.AddField(
            model_name='smtpconfiguration',
            name='last_error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Último erro'),
        ),
        migrations.AddField(
            model_name='smtpconfiguration',
            name='last_test_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tempo teste (segundos)'),
        ),
        migrations.AddField(
            model_name='usageprofiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usageprofiles',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='usageprofiles',
            name='purpose',
            field=models.CharField(default=django.utils.timezone.now, help_text='Informe a finalidade de utilização deste perfil.', max_length=100, verbose_name='Propósito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usageprofiles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddConstraint(
            model_name='usageprofiles',
            constraint=models.UniqueConstraint(fields=('purpose',), name='unique_usage_profile_purpose'),
        ),
    ]
