# Generated by Django 5.0.3 on 2026-05-26 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0010_alter_usageprofiles_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpconfiguration',
            name='connection_timeout',
            field=models.IntegerField(default=30, verbose_name='Timeout de conexão (s)'),
        ),
        migrations.AddField(
            model_name='smtpconfiguration',
            name='last_response_time_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Último tempo de resposta (ms)'),
        ),
        migrations.AddField(
            model_name='smtpconfiguration',
            name='last_successful_connection_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última conexão bem-sucedida'),
        ),
        migrations.AddField(
            model_name='smtpconfiguration',
            name='last_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.AddField(
            model_name='smtpconfiguration',
            name='last_validation_message',
            field=models.TextField(blank=True, verbose_name='Última mensagem de validação'),
        ),
        migrations.AddField(
            model_name='smtpconfiguration',
            name='validation_attempts',
            field=models.IntegerField(default=0, verbose_name='Tentativas de validação'),
        ),
    ]
