# Generated by Django 5.0.3 on 2026-05-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0011_smtpconfiguration_connection_timeout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=255, verbose_name='Prioridade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': '03. Tipo de Prioridade',
                'verbose_name_plural': '03. Tipos de Prioridade',
            },
        ),
    ]
