# Generated by Django 5.0.3 on 2026-05-30 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0013_shippingqueue_attachments_shippingqueue_bcc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingqueue',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário'),
        ),
    ]
