# Generated by Django 5.0.3 on 2026-05-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_alter_addresses_table_alter_states_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesVisitorRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Restrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': '5. Tipo de Restrição/Visitante',
                'verbose_name_plural': '5. Tipos de Restrição/Visitantes',
                'ordering': ['description'],
                'unique_together': {('description',)},
            },
        ),
    ]
