# Generated by Django 5.0.3 on 2026-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0005_alter_addresses_options_alter_states_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Residente',
                'verbose_name_plural': '06. Tipos de Residentes',
                'ordering': ['description'],
                'unique_together': {('description',)},
            },
        ),
    ]
