# Generated by Django 5.0.3 on 2026-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0006_residenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterModelTable(
            name='addresses',
            table='parameters_addresses',
        ),
        migrations.AlterModelTable(
            name='residenttype',
            table='parameters_residenttype',
        ),
        migrations.AlterModelTable(
            name='states',
            table='parameters_states',
        ),
        migrations.AlterModelTable(
            name='structioncondominium',
            table='parameters_structioncondominium',
        ),
        migrations.AlterModelTable(
            name='typescondominium',
            table='parameters_typescondominium',
        ),
        migrations.AlterModelTable(
            name='typesvisitorrestrictions',
            table='parameters_typesvisitorrestrictions',
        ),
    ]
