# Generated by Django 5.0.3 on 2026-06-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0007_alter_addresses_complement_alter_addresses_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': '07. Tipos de Documentos',
                'ordering': ['description'],
                'unique_together': {('description',)},
            },
        ),
    ]
