# Generated by Django 5.0.3 on 2026-06-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0008_documenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfractionsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Infração',
                'verbose_name_plural': '08. Tipos de Infrações',
                'ordering': ['description'],
                'unique_together': {('description',)},
            },
        ),
    ]
