# Generated by Django 5.0.3 on 2026-06-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0009_infractionstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='infractionstype',
            name='infraction_type',
            field=models.CharField(choices=[('A', 'Advertência'), ('M', 'Multa'), ('N', 'Notificação')], default='N', max_length=30, verbose_name='Tipo de Infração'),
        ),
    ]
