# Generated by Django 5.0.3 on 2026-07-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0010_infractionstype_infraction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prioridade')),
                ('priority_value', models.IntegerField(blank=True, default=0, null=True, verbose_name='Valor da Prioridade')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': '06. Tipo de Medidor',
                'verbose_name_plural': '06. Tipos de Medidores',
                'ordering': ['name'],
            },
        ),
    ]
