# Generated by Django 5.0.3 on 2026-07-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0011_metertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metertype',
            options={'ordering': ['description'], 'verbose_name': '09. Tipo de Medidor', 'verbose_name_plural': '09. Tipos de Medidores'},
        ),
        migrations.RemoveField(
            model_name='metertype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='metertype',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='metertype',
            name='priority_value',
        ),
        migrations.AddField(
            model_name='metertype',
            name='description',
            field=models.CharField(default='Tipo não definido', max_length=255, unique=True, verbose_name='Descrição'),
        ),
    ]
