# Generated by Django 5.0.3 on 2026-07-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0012_alter_metertype_options_remove_metertype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metertype',
            name='description',
            field=models.CharField(max_length=255, unique=True, verbose_name='Descrição'),
        ),
    ]
