# Generated by Django 5.0.3 on 2026-07-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0014_assetbrand_assetcategory_assetmaintenancefrequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': '16. Tipo de Conta Bancária',
                'verbose_name_plural': '16. Tipos de Contas Bancárias',
                'db_table': 'parameters_bankaccounttype',
                'ordering': ['description'],
            },
        ),
        migrations.AlterModelOptions(
            name='assetbrand',
            options={'ordering': ['description'], 'verbose_name': '13. Marca de Patrimônio', 'verbose_name_plural': '13. Marcas de Patrimônios'},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['description'], 'verbose_name': '10. Categoria de Patrimônio', 'verbose_name_plural': '10. Categorias de Patrimônios'},
        ),
        migrations.AlterModelOptions(
            name='assetmaintenancefrequency',
            options={'ordering': ['description'], 'verbose_name': '12. Frequência de Manutenção', 'verbose_name_plural': '12. Frequências de Manutenção'},
        ),
        migrations.AlterModelOptions(
            name='assetstatecondition',
            options={'ordering': ['description'], 'verbose_name': '11. Estado de Conservação', 'verbose_name_plural': '11. Estados de Conservação'},
        ),
        migrations.AlterModelOptions(
            name='assetstatus',
            options={'ordering': ['description'], 'verbose_name': '14. Status de Patrimônio', 'verbose_name_plural': '14. Status de Patrimônios'},
        ),
        migrations.AlterModelOptions(
            name='assettype',
            options={'ordering': ['description'], 'verbose_name': '15.Tipo de Patrimônio', 'verbose_name_plural': '15. Tipos de Patrimônios'},
        ),
    ]
