# Generated by Django 5.0.3 on 2026-08-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0025_chartofaccountssubgroup_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccountsmaingroup',
            options={'ordering': ['account_class', 'description'], 'verbose_name': '19. Grupo Principal de Conta Contábil', 'verbose_name_plural': '19. Grupos Principais de Contas Contábeis'},
        ),
    ]
