# Generated by Django 5.0.3 on 2026-08-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0027_ensure_states_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': '22. Tipo de Votação',
                'verbose_name_plural': '22. Tipos de Votações',
                'db_table': 'parameters_votingtype',
                'ordering': ['description'],
            },
        ),
    ]
