# Generated by Django 5.0.3 on 2026-08-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0028_votingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
                ('is_pending', models.BooleanField(default=True, verbose_name='Está pendente')),
                ('is_running', models.BooleanField(default=False, verbose_name='Está em execução')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Está completo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': '23. Status da Assembleia',
                'verbose_name_plural': '23. Status das Assembleias',
                'db_table': 'parameters_assemblystatus',
                'ordering': ['description'],
            },
        ),
        migrations.AddConstraint(
            model_name='assemblystatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_running', True)), fields=('is_running',), name='unique_running_assembly_status'),
        ),
        migrations.AddConstraint(
            model_name='assemblystatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_complete', True)), fields=('is_complete',), name='unique_complete_assembly_status'),
        ),
    ]
