# Generated by Django 5.0.3 on 2026-08-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0029_assemblystatus_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assemblystatus',
            name='unique_running_assembly_status',
        ),
        migrations.RemoveConstraint(
            model_name='assemblystatus',
            name='unique_complete_assembly_status',
        ),
        migrations.AddConstraint(
            model_name='assemblystatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_running', True)), fields=('is_running',), name='unique_running_assembly_status', violation_error_message='Já existe um status marcado como "Em execução".'),
        ),
        migrations.AddConstraint(
            model_name='assemblystatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_complete', True)), fields=('is_complete',), name='unique_complete_assembly_status', violation_error_message='Já existe um status marcado como "Completo".'),
        ),
    ]
