# Generated by Django 5.0.3 on 2026-08-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0030_remove_assemblystatus_unique_running_assembly_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': '24. Opção de Pauta',
                'verbose_name_plural': '24. Opções de Pautas',
                'db_table': 'parameters_topicoptions',
                'ordering': ['description'],
            },
        ),
    ]
