# Generated by Django 5.0.3 on 2026-09-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0031_topicoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': '25. Categoria de Serviço Portaria',
                'verbose_name_plural': '25. Categorias de Serviço Portaria',
                'db_table': 'parameters_conciergeservicecategories',
                'ordering': ['description'],
            },
        ),
    ]
