# Generated by Django 5.0.3 on 2026-10-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0032_conciergeservicecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': '26. Categoria de Telefone',
                'verbose_name_plural': '26. Categorias de Telefone',
                'ordering': ['name'],
            },
        ),
    ]
