# Generated by Django 5.0.3 on 2026-05-18 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalities', '0009_entity_date_time_appointment_alter_entity_api_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssector',
            options={'ordering': ['description'], 'verbose_name': '01. Ramo de Atividade', 'verbose_name_plural': '01. Ramos de Atividade'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['business_sector', 'name', 'cpf_cnpj'], 'verbose_name': '02. Entidade', 'verbose_name_plural': '02. Entidades'},
        ),
    ]
