# Generated by Django 5.0.3 on 2026-05-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': '01. Acordo', 'verbose_name_plural': '01. Acordos'},
        ),
        migrations.AlterModelOptions(
            name='apportionment',
            options={'verbose_name': '09. Rateio', 'verbose_name_plural': '09. Rateios'},
        ),
        migrations.AlterModelOptions(
            name='cash',
            options={'verbose_name': '03. Caixa', 'verbose_name_plural': '03. Caixa'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '04. Cobrança', 'verbose_name_plural': '04. Cobranças'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': '06. Empréstimo', 'verbose_name_plural': '06. Empréstimos'},
        ),
        migrations.AlterModelOptions(
            name='newrelease',
            options={'verbose_name': '07. Lançamento', 'verbose_name_plural': '07. Lançamentos'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '08. Pagamento', 'verbose_name_plural': '08. Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='paymentslip',
            options={'verbose_name': '02. Boleto', 'verbose_name_plural': '02. Boletos'},
        ),
        migrations.AlterModelOptions(
            name='shopping',
            options={'verbose_name': '05. Compra', 'verbose_name_plural': '05. Compras'},
        ),
    ]
