# Generated by Django 5.0.3 on 2026-04-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominium', '0006_alter_addresses_complement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondominiumUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(db_index=True, max_length=20, verbose_name='Número da unidade')),
                ('floor', models.CharField(choices=[('inferior', 'Inferior'), ('terreo', 'Térreo'), ('1', '1° andar'), ('2', '2° andar'), ('3', '3° andar'), ('4', '4° andar'), ('5', '5° andar'), ('terraco', 'Terraço')], max_length=20, verbose_name='Pavimento')),
                ('unit_type', models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('commercial', 'Comercial'), ('office', 'Sala Comercial'), ('store', 'Loja')], max_length=20, verbose_name='Tipo')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Número de quartos')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Número de banheiros')),
                ('suites', models.PositiveIntegerField(default=0, verbose_name='Número de suítes')),
                ('garage_spaces', models.PositiveIntegerField(default=0, verbose_name='Número de vagas de garagem')),
                ('area_private', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área privativa')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área total')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('occupied', 'Ocupado'), ('maintenance', 'Manutenção'), ('reserved', 'Reservado')], default='available', max_length=20, verbose_name='Status')),
                ('for_sale', models.BooleanField(default=False, verbose_name='Para venda')),
                ('for_rent', models.BooleanField(default=False, verbose_name='Para aluguel')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Preço de venda')),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Preço de aluguel')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='condominium.condominium', verbose_name='Condomínio')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='condominium.structioncondominium', verbose_name='Bloco / Torre')),
            ],
            options={
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Imobiliária')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Site')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='condominium.addresses', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Imobiliária',
                'verbose_name_plural': 'Imobiliárias',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('sex', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Sexo')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('profission', models.CharField(blank=True, max_length=100, verbose_name='Profissão')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('is_resident', models.BooleanField(default=True, verbose_name='É residente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='residents.condominiumunit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Morador',
                'verbose_name_plural': 'Moradores',
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fire', 'Incêndio'), ('medical', 'Emergência Médica'), ('security', 'Segurança'), ('other', 'Outros')], default='other', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condo_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='residents.condominiumunit', verbose_name='Unidade/Condomínio')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies_reported', to='residents.resident', verbose_name='Quem reportou')),
            ],
            options={
                'verbose_name': 'Emergência',
                'verbose_name_plural': 'Emergências',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('species', models.CharField(choices=[('dog', 'Cachorro'), ('cat', 'Gato'), ('bird', 'Pássaro'), ('other', 'Outro')], default='dog', max_length=20, verbose_name='Espécie')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Raça')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('U', 'Desconhecido')], default='U', max_length=1, verbose_name='Sexo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='residents.resident', verbose_name='Morador')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Placa')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Cor')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('garage_space', models.CharField(blank=True, max_length=50, verbose_name='Vaga de garagem')),
                ('vehicle_type', models.CharField(choices=[('car', 'Carro'), ('motorcycle', 'Moto'), ('truck', 'Caminhão'), ('other', 'Outro')], default='car', max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='residents.resident', verbose_name='Morador')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da visita')),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='Propósito da visita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='residents.resident', verbose_name='Morador anfitrião')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.AddConstraint(
            model_name='condominiumunit',
            constraint=models.UniqueConstraint(fields=('structure', 'unit_number'), name='unique_unit_per_structure'),
        ),
    ]
