# Generated by Django 5.0.3 on 2026-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominiumunit',
            name='structure',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bloco / Torre'),
        ),
    ]
