# Generated by Django 5.0.3 on 2026-04-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_alter_condominiumunit_structure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condominiumunit',
            old_name='structure',
            new_name='tower',
        ),
    ]
