# Generated by Django 5.0.3 on 2026-04-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_alter_condominiumunit_bathrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominiumunit',
            name='area_private',
        ),
        migrations.AlterField(
            model_name='condominiumunit',
            name='area_total',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10, verbose_name='Área total'),
        ),
    ]
