# Generated by Django 5.0.3 on 2026-04-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_remove_condominiumunit_area_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
    ]
