# Generated by Django 5.0.3 on 2026-04-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_alter_resident_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominiumunit',
            options={'ordering': ['unit_number'], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
    ]
