# Generated by Django 5.0.3 on 2026-04-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_remove_animal_owner_animal_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='residents.condominiumunit', verbose_name='Unidade'),
        ),
    ]
