# Generated by Django 5.0.3 on 2026-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0012_remove_emergency_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='type',
            field=models.CharField(choices=[('fire', 'Incêndio'), ('medical', 'Emergência Médica'), ('security', 'Segurança'), ('leaks', 'Vazamentos'), ('power', 'Falta de energia'), ('personal accidents', 'Acidentes pessoais'), ('structural damage', 'Danos estruturais'), ('conflicts', 'Conflitos'), ('other', 'Outros')], default='other', max_length=20, verbose_name='Tipo'),
        ),
    ]
