# Generated by Django 5.0.3 on 2026-04-12 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0013_alter_emergency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateagency',
            name='condo_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_units', to='residents.condominiumunit', verbose_name='Unidade/Condomínio'),
        ),
    ]
