# Generated by Django 5.0.3 on 2026-04-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0014_realestateagency_condo_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='condo_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='residents.condominiumunit', verbose_name='Unidade/Condomínio'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Carro'), ('motorcycle', 'Moto'), ('truck', 'Caminhão'), ('pickup truck', 'Caminhonete'), ('trailer', 'Reboque'), ('mpped', 'Ciclomotor'), ('bicycle', 'Bicicleta'), ('other', 'Outro')], default='car', max_length=20, verbose_name='Tipo'),
        ),
    ]
