# Generated by Django 5.0.3 on 2026-04-12 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0015_remove_vehicle_owner_vehicle_condo_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='unit',
            new_name='condo_unit',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='host',
        ),
        migrations.AddField(
            model_name='visitor',
            name='condo_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='residents.condominiumunit', verbose_name='Unidade/Condomínio'),
        ),
    ]
