# Generated by Django 5.0.3 on 2026-04-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0016_rename_unit_animal_condo_unit_remove_visitor_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateagency',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pessoa de contato'),
        ),
    ]
