# Generated by Django 5.0.3 on 2026-04-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0017_realestateagency_contact_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': '5. Animal', 'verbose_name_plural': '5. Animais'},
        ),
        migrations.AlterModelOptions(
            name='condominiumunit',
            options={'ordering': ['unit_number'], 'verbose_name': '1. Unidade', 'verbose_name_plural': '1. Unidades'},
        ),
        migrations.AlterModelOptions(
            name='emergency',
            options={'verbose_name': '4. Emergência', 'verbose_name_plural': '4. Emergências'},
        ),
        migrations.AlterModelOptions(
            name='realestateagency',
            options={'verbose_name': '7. Imobiliária', 'verbose_name_plural': '7. Imobiliárias'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': '2. Morador', 'verbose_name_plural': '2. Moradores'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': '3. Veículo', 'verbose_name_plural': '3. Veículos'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': '6. Visitante', 'verbose_name_plural': '6. Visitantes'},
        ),
    ]
