# Generated by Django 5.0.3 on 2026-04-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0018_alter_animal_options_alter_condominiumunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='condo_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='residents.condominiumunit', verbose_name='Condomínio/Unidade'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='condo_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='residents.condominiumunit', verbose_name='Condomínio/Unidade'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='condo_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_units', to='residents.condominiumunit', verbose_name='Condomínio/Unidade'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condo_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='residents.condominiumunit', verbose_name='Condomínio/Unidade'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='condo_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='residents.condominiumunit', verbose_name='Condomínio/Unidade'),
        ),
    ]
