# Generated by Django 5.0.3 on 2026-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0019_alter_animal_condo_unit_alter_emergency_condo_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='type_of_resident',
            field=models.CharField(blank=True, choices=[('owner', 'Proprietário(a)'), ('tenant', 'Morador(a)'), ('occupant', 'Ocupante')], default='tenant', max_length=20, null=True, verbose_name='Tipo de morador'),
        ),
    ]
