# Generated by Django 5.0.3 on 2026-04-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0021_animal_is_active_emergency_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestateagency',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
