# Generated by Django 5.0.3 on 2026-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0022_rename_active_realestateagency_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumunit',
            name='identification',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificação'),
        ),
    ]
