# Generated by Django 5.0.3 on 2026-04-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0023_condominiumunit_identification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['condo_unit', 'name', 'species', 'created_at'], 'verbose_name': '5. Animal', 'verbose_name_plural': '5. Animais'},
        ),
        migrations.AlterModelOptions(
            name='condominiumunit',
            options={'ordering': ['tower', 'unit_number', 'floor', 'created_at'], 'verbose_name': '1. Unidade', 'verbose_name_plural': '1. Unidades'},
        ),
        migrations.AlterModelOptions(
            name='emergency',
            options={'ordering': ['condo_unit', 'type', 'occurred_at', 'created_at'], 'verbose_name': '4. Emergência', 'verbose_name_plural': '4. Emergências'},
        ),
        migrations.AlterModelOptions(
            name='realestateagency',
            options={'ordering': ['condo_unit', 'name', 'created_at'], 'verbose_name': '7. Imobiliária', 'verbose_name_plural': '7. Imobiliárias'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['unit', 'name', 'created_at'], 'verbose_name': '2. Morador', 'verbose_name_plural': '2. Moradores'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['condo_unit', 'vehicle_type', 'license_plate', 'created_at'], 'verbose_name': '3. Veículo', 'verbose_name_plural': '3. Veículos'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['condo_unit', 'name', 'visit_date', 'created_at'], 'verbose_name': '6. Visitante', 'verbose_name_plural': '6. Visitantes'},
        ),
    ]
