# Generated by Django 5.0.3 on 2026-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0024_alter_animal_options_alter_condominiumunit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateagency',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('condo_unit', 'name'), ('condo_unit', 'species', 'breed')},
        ),
        migrations.AlterUniqueTogether(
            name='condominiumunit',
            unique_together={('tower', 'unit_number')},
        ),
        migrations.AlterUniqueTogether(
            name='emergency',
            unique_together={('condo_unit', 'description', 'occurred_at'), ('condo_unit', 'type', 'occurred_at')},
        ),
        migrations.AlterUniqueTogether(
            name='realestateagency',
            unique_together={('condo_unit', 'email'), ('condo_unit', 'name'), ('condo_unit', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='resident',
            unique_together={('unit', 'cpf'), ('unit', 'name'), ('unit', 'rg')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('condo_unit', 'license_plate'), ('condo_unit', 'vehicle_type', 'model', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('condo_unit', 'cpf'), ('condo_unit', 'name'), ('condo_unit', 'rg')},
        ),
    ]
