# Generated by Django 5.0.3 on 2026-04-12 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0025_realestateagency_cnpj_alter_animal_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('document_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de documento')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Arquivo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condo_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='residents.condominiumunit', verbose_name='Condomínio/Unidade')),
            ],
            options={
                'verbose_name': '8. Documento',
                'verbose_name_plural': '8. Documentos',
                'ordering': ['condo_unit', 'title', 'created_at'],
                'unique_together': {('condo_unit', 'document_type', 'created_at'), ('condo_unit', 'title')},
            },
        ),
    ]
