# Generated by Django 5.0.3 on 2026-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0027_alter_documents_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominiumunit',
            name='identification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Identificação'),
        ),
        migrations.AlterField(
            model_name='condominiumunit',
            name='tower',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bloco / Torre'),
        ),
    ]
