# Generated by Django 5.0.3 on 2026-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0028_alter_condominiumunit_identification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=8, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True, verbose_name='Ano'),
        ),
    ]
