# Generated by Django 5.0.3 on 2026-04-22 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0030_alter_vehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='condo_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='residents.condominiumunit', verbose_name='Condomínio/Unidade'),
        ),
    ]
