# Generated by Django 5.0.3 on 2026-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0033_resident_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='residents/vehicles/', verbose_name='Foto'),
        ),
    ]
