# Generated by Django 5.0.3 on 2026-05-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0035_animal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='residents/visitors/', verbose_name='Foto'),
        ),
    ]
