# Generated by Django 5.0.3 on 2026-05-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0037_realestateagency_trade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='death',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='Óbito'),
        ),
        migrations.AddField(
            model_name='resident',
            name='regular',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='CPF Regular'),
        ),
        migrations.AddField(
            model_name='resident',
            name='situation',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Situação Receita Federal'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='death',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='Óbito'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='regular',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='CPF Regular'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='situation',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Situação Receita Federal'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cri도 em'),
        ),
    ]
