# Generated by Django 5.0.3 on 2026-05-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0038_resident_death_resident_regular_resident_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='api_status',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='Status da API'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='api_status',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='Status da API'),
        ),
    ]
