# Generated by Django 5.0.3 on 2026-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0039_resident_api_status_visitor_api_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['condo_unit', 'name', 'created_at'], 'verbose_name': '6. Visitante', 'verbose_name_plural': '6. Visitantes'},
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='resident',
            name='retorno_api',
            field=models.TextField(blank=True, null=True, verbose_name='Retorno da API'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='retorno_api',
            field=models.TextField(blank=True, null=True, verbose_name='Retorno da API'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='cnpj',
            field=models.CharField(max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(default='pendente3@brasilcondo.com.br', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='rg',
            field=models.CharField(max_length=20, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='rg',
            field=models.CharField(max_length=20, verbose_name='RG'),
        ),
    ]
