# Generated by Django 5.0.3 on 2026-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0040_alter_visitor_options_remove_visitor_visit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='date_time_appointment',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data/hora da consulta'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='api_status',
            field=models.CharField(blank=True, default='nulo', editable=False, max_length=100, null=True, verbose_name='Status da API'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='death',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Óbito'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='regular',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='CPF Regular'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='retorno_api',
            field=models.TextField(blank=True, default='nulo', editable=False, null=True, verbose_name='Retorno da API'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='situation',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Suspenso', 'Suspenso'), ('Pendente de Regularização', 'Pendente de Regularização'), ('Cancelado', 'Cancelado'), ('Titular Falecido', 'Titular Falecido'), ('Nulo', 'Nulo')], max_length=100, null=True, verbose_name='Situação Receita Federal'),
        ),
    ]
