# Generated by Django 5.0.3 on 2026-05-17 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_typesvisitorrestrictions'),
        ('residents', '0043_resident_certificate_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='certificate_presentation_date',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='certificate_validity',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='observations_certificate',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='certificate_presentation_date',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='certificate_validity',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='observations_certificate',
        ),
        migrations.AddField(
            model_name='visitor',
            name='restrictionVisitor_file',
            field=models.FileField(blank=True, null=True, upload_to='residents/restrictions/', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='restrictionVisitor_observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='restrictionVisitor_presentation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de apresentação'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='restrictionVisitor_validity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de validade'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='types_visitor_restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.typesvisitorrestrictions', verbose_name='Tipos de Restrição'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criдо em'),
        ),
    ]
