# Generated by Django 5.0.3 on 2026-05-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0045_resident_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['condo_unit', 'name', 'species', 'created_at'], 'verbose_name': '05. Animal', 'verbose_name_plural': '05. Animais'},
        ),
        migrations.AlterModelOptions(
            name='condominiumunit',
            options={'ordering': ['tower', 'unit_number', 'floor', 'created_at'], 'verbose_name': '01. Unidade', 'verbose_name_plural': '01. Unidades'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['condo_unit', 'title', 'created_at'], 'verbose_name': '08. Documento', 'verbose_name_plural': '08. Documentos'},
        ),
        migrations.AlterModelOptions(
            name='emergency',
            options={'ordering': ['condo_unit', 'type', 'occurred_at', 'created_at'], 'verbose_name': '04. Emergência', 'verbose_name_plural': '04. Emergências'},
        ),
        migrations.AlterModelOptions(
            name='realestateagency',
            options={'ordering': ['condo_unit', 'name', 'created_at'], 'verbose_name': '07. Imobiliária', 'verbose_name_plural': '07. Imobiliárias'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['unit', 'name', 'created_at'], 'verbose_name': '0  02. Morador', 'verbose_name_plural': '02. Moradores'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['condo_unit', 'vehicle_type', 'license_plate', 'created_at'], 'verbose_name': '03. Veículo', 'verbose_name_plural': '03. Veículos'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['condo_unit', 'name', 'created_at'], 'verbose_name': '06. Visitante', 'verbose_name_plural': '06. Visitantes'},
        ),
    ]
