# Generated by Django 5.0.3 on 2026-05-21 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0006_residenttype'),
        ('residents', '0046_alter_animal_options_alter_condominiumunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='type_of_resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resident', to='parameters.residenttype', verbose_name='Tipo de morador'),
        ),
    ]
