# Generated by Django 5.0.3 on 2026-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0047_alter_resident_type_of_resident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['unit', 'name', 'created_at'], 'verbose_name': '02. Morador', 'verbose_name_plural': '02. Moradores'},
        ),
        migrations.AlterField(
            model_name='resident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterModelTable(
            name='animal',
            table='residents_animal',
        ),
        migrations.AlterModelTable(
            name='condominiumunit',
            table='residents_condominiumunit',
        ),
        migrations.AlterModelTable(
            name='documents',
            table='residents_documents',
        ),
        migrations.AlterModelTable(
            name='emergency',
            table='residents_emergency',
        ),
        migrations.AlterModelTable(
            name='realestateagency',
            table='residents_realestateagency',
        ),
        migrations.AlterModelTable(
            name='resident',
            table='residents_resident',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='residents_vehicle',
        ),
        migrations.AlterModelTable(
            name='visitor',
            table='residents_visitor',
        ),
    ]
