# Generated by Django 5.0.3 on 2026-05-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gerenciamento de Dados', editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Informações do App',
                'verbose_name_plural': 'Informações do App',
                'managed': False,
            },
        ),
    ]
