# Generated by Django 5.0.3 on 2026-05-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
            },
        ),
        migrations.CreateModel(
            name='BackupModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
            },
        ),
        migrations.CreateModel(
            name='ExportModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Exportação',
                'verbose_name_plural': 'Exportações',
            },
        ),
        migrations.CreateModel(
            name='ImportModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Importação',
                'verbose_name_plural': 'Importações',
            },
        ),
        migrations.CreateModel(
            name='IntegrationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Integração',
                'verbose_name_plural': 'Integrações',
            },
        ),
        migrations.CreateModel(
            name='LogModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='RestoreModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Restauração',
                'verbose_name_plural': 'Restaurações',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tarefa Agendada',
                'verbose_name_plural': 'Tarefas Agendadas',
            },
        ),
        migrations.DeleteModel(
            name='AppPlaceholder',
        ),
    ]
