# Generated by Django 5.0.3 on 2026-05-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_auditmodule_backupmodule_exportmodule_importmodule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditmodule',
            options={'verbose_name': '4. Auditoria', 'verbose_name_plural': '4. Auditorias'},
        ),
        migrations.AlterModelOptions(
            name='backupmodule',
            options={'verbose_name': '7. Backup', 'verbose_name_plural': '7. Backups'},
        ),
        migrations.AlterModelOptions(
            name='exportmodule',
            options={'verbose_name': '2. Exportação', 'verbose_name_plural': '2. Exportações'},
        ),
        migrations.AlterModelOptions(
            name='importmodule',
            options={'verbose_name': '1. Importação', 'verbose_name_plural': '1. Importações'},
        ),
        migrations.AlterModelOptions(
            name='integrationmodule',
            options={'verbose_name': '6. Integração', 'verbose_name_plural': '6. Integrações'},
        ),
        migrations.AlterModelOptions(
            name='logmodule',
            options={'verbose_name': '3. Log', 'verbose_name_plural': '3. Logs'},
        ),
        migrations.AlterModelOptions(
            name='restoremodule',
            options={'verbose_name': '8. Restauração', 'verbose_name_plural': '8. Restaurações'},
        ),
        migrations.AlterModelOptions(
            name='scheduledtaskmodule',
            options={'verbose_name': '5. Tarefa Agendada', 'verbose_name_plural': '5. Tarefas Agendadas'},
        ),
    ]
