# Generated by Django 5.0.3 on 2026-05-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_alter_auditmodule_options_alter_backupmodule_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogModule',
        ),
        migrations.AlterModelOptions(
            name='auditmodule',
            options={'verbose_name': '03. Auditoria', 'verbose_name_plural': '03. Auditorias'},
        ),
        migrations.AlterModelOptions(
            name='backupmodule',
            options={'verbose_name': '06. Backup', 'verbose_name_plural': '06. Backups'},
        ),
        migrations.AlterModelOptions(
            name='exportmodule',
            options={'verbose_name': '02. Exportação', 'verbose_name_plural': '02. Exportações'},
        ),
        migrations.AlterModelOptions(
            name='importmodule',
            options={'verbose_name': '01. Importação', 'verbose_name_plural': '01. Importações'},
        ),
        migrations.AlterModelOptions(
            name='integrationmodule',
            options={'verbose_name': '05. Integração', 'verbose_name_plural': '05. Integrações'},
        ),
        migrations.AlterModelOptions(
            name='restoremodule',
            options={'verbose_name': '07. Restauração', 'verbose_name_plural': '07. Restaurações'},
        ),
        migrations.AlterModelOptions(
            name='scheduledtaskmodule',
            options={'verbose_name': '04. Tarefa Agendada', 'verbose_name_plural': '04. Tarefas Agendadas'},
        ),
    ]
