# Generated by Django 5.0.3 on 2026-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_delete_logmodule_alter_auditmodule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.AlterModelOptions(
            name='auditmodule',
            options={'verbose_name': 'Auditoria', 'verbose_name_plural': 'Auditorias'},
        ),
        migrations.AlterModelOptions(
            name='backupmodule',
            options={'verbose_name': 'Backup', 'verbose_name_plural': 'Backups'},
        ),
        migrations.AlterModelOptions(
            name='exportmodule',
            options={'verbose_name': 'Exportação', 'verbose_name_plural': 'Exportações'},
        ),
        migrations.AlterModelOptions(
            name='importmodule',
            options={'verbose_name': 'Importação', 'verbose_name_plural': 'Importações'},
        ),
        migrations.AlterModelOptions(
            name='integrationmodule',
            options={'verbose_name': 'Integração', 'verbose_name_plural': 'Integrações'},
        ),
        migrations.AlterModelOptions(
            name='restoremodule',
            options={'verbose_name': 'Restauração', 'verbose_name_plural': 'Restaurações'},
        ),
        migrations.AlterModelOptions(
            name='scheduledtaskmodule',
            options={'verbose_name': 'Tarefa Agendada', 'verbose_name_plural': 'Tarefas Agendadas'},
        ),
    ]
