# Generated by Django 5.0.3 on 2026-08-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_scheduledtaskmodule_fields_scheduledtaskrecipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtaskmodule',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tarefa Agendada', 'verbose_name_plural': 'Tarefas Agendadas'},
        ),
    ]
