# Generated by Django 5.0.3 on 2026-09-07 17:43

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_alter_scheduledtaskmodule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditmodule',
            options={'verbose_name': '03. Auditoria', 'verbose_name_plural': '03. Auditorias'},
        ),
        migrations.AlterModelOptions(
            name='backupmodule',
            options={'verbose_name': '01. Backup', 'verbose_name_plural': '01. Backups'},
        ),
        migrations.AlterModelOptions(
            name='exportmodule',
            options={'verbose_name': '04. Exportação', 'verbose_name_plural': '04.Exportações'},
        ),
        migrations.AlterModelOptions(
            name='importmodule',
            options={'verbose_name': '05. Importação', 'verbose_name_plural': '05. Importações'},
        ),
        migrations.AlterModelOptions(
            name='integrationmodule',
            options={'verbose_name': '06. Integração', 'verbose_name_plural': '06. Integrações'},
        ),
        migrations.AlterModelOptions(
            name='logmodule',
            options={'verbose_name': '03. Log', 'verbose_name_plural': '03.Logs'},
        ),
        migrations.AlterModelOptions(
            name='restoremodule',
            options={'verbose_name': '02. Restauração', 'verbose_name_plural': '02. Restaurações'},
        ),
        migrations.AlterModelOptions(
            name='scheduledtaskmodule',
            options={'ordering': ['-created_at'], 'verbose_name': '07. Tarefa Agendada', 'verbose_name_plural': '07. Tarefas Agendadas'},
        ),
        migrations.AddField(
            model_name='backupmodule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupmodule',
            name='dateTime',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data do backup', verbose_name='Data/Hora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupmodule',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição do backup', null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='backupmodule',
            name='file_url',
            field=models.CharField(blank=True, default='', help_text='Caminho do arquivo de backup gerado', max_length=255, verbose_name='Arquivo de Backup'),
        ),
        migrations.AddField(
            model_name='backupmodule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o registro está ativo', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='backupmodule',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Em Execução'), ('concluido', 'Concluído'), ('falha', 'Falha'), ('inativo', 'Inativo'), ('restaurando', 'Restaurando')], default='pendente', help_text='Status atual do backup', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='backupmodule',
            name='title',
            field=models.CharField(default=datetime.date(2026, 9, 7), help_text='Título do backup', max_length=250, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupmodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddConstraint(
            model_name='backupmodule',
            constraint=models.UniqueConstraint(fields=('title', 'dateTime'), name='unique_backup_title_datetime'),
        ),
    ]
