# Generated by Django 5.0.3 on 2026-09-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_alter_auditmodule_options_alter_backupmodule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportmodule',
            options={'verbose_name': '04. Exportação', 'verbose_name_plural': '04. Exportações'},
        ),
        migrations.AlterModelOptions(
            name='logmodule',
            options={'verbose_name': '03. Log', 'verbose_name_plural': '03. Logs'},
        ),
    ]
