# Generated by Django 5.0.3 on 2026-09-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0039_remove_virtualmeetingemailschedule_virtual_meeting_and_more'),
        ('data_management', '0009_alter_exportmodule_options_alter_logmodule_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduledtaskmodule',
            index=models.Index(fields=['status', 'scheduled_at'], name='idx_schedtask_status_schedat'),
        ),
    ]
