# Generated by Django 5.0.3 on 2026-09-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0039_remove_virtualmeetingemailschedule_virtual_meeting_and_more'),
        ('data_management', '0010_scheduledtaskmodule_idx_schedtask_status_schedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtaskmodule',
            name='virtual_meeting',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='administrative.virtualmeeting', verbose_name='Votação Virtual'),
        ),
    ]
