# Generated by Django 5.0.3 on 2026-09-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0012_exportmodule_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditModule',
        ),
        migrations.DeleteModel(
            name='RestoreModule',
        ),
        migrations.AlterModelOptions(
            name='importmodule',
            options={'verbose_name': '03. Importação', 'verbose_name_plural': '03. Importações'},
        ),
        migrations.AlterModelOptions(
            name='integrationmodule',
            options={'verbose_name': '04. Integração', 'verbose_name_plural': '04. Integrações'},
        ),
        migrations.AlterModelOptions(
            name='scheduledtaskmodule',
            options={'ordering': ['-created_at'], 'verbose_name': '05. Tarefa Agendada', 'verbose_name_plural': '05. Tarefas Agendadas'},
        ),
    ]
