# Generated by Django 5.0.3 on 2026-05-28 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0036_alter_collaborators_options_and_more'),
        ('email_service', '0012_typespriority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingqueue',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/', verbose_name='Anexos'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='bcc',
            field=models.TextField(blank=True, null=True, verbose_name='BCC'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='cc',
            field=models.TextField(blank=True, null=True, verbose_name='CC'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='condominium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='condominium.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_queue_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='html_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem HTML'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='last_error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Último erro'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='logs',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Logs'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='max_retry_attempts',
            field=models.IntegerField(default=3, verbose_name='Máximo tentativas'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='module_origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Origem do módulo'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima tentativa'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_service.typespriority', verbose_name='Tipo de Prioridade'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processamento iniciado em'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID mensagem do provedor'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='provider_response',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta do provedor'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Referência ID'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Responder para'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='response_time_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo de resposta (ms)'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='Tentativas'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agendado para'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado em'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='smtp_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_service.smtpconfiguration', verbose_name='Configuração SMTP'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_queue', to='email_service.connectionstatus', verbose_name='Status conexão'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Destinatário'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='usage_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_service.usageprofiles', verbose_name='Perfil de uso'),
        ),
        migrations.AddField(
            model_name='shippingqueue',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='shippingqueue',
            constraint=models.UniqueConstraint(fields=('module_origin', 'reference_id', 'to_email'), name='unique_queue_email_per_reference'),
        ),
    ]
