# Generated by Django 5.0.3 on 2026-06-14 13:52

import core.services.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominium', '0037_alter_types_collaborators_unique_together_and_more'),
        ('email_service', '0014_alter_shippingqueue_uuid_and_more'),
        ('parameters', '0007_alter_addresses_complement_alter_addresses_table_and_more'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '08. Previsão Orçamentária',
                'verbose_name_plural': '08. Previsões Orçamentárias',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '09. Plano de Conta',
                'verbose_name_plural': '09. Plano de Contas',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '03. Documento',
                'verbose_name_plural': '03. Documentos',
            },
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '04. Infração',
                'verbose_name_plural': '04. Infrações',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '05. Medidor',
                'verbose_name_plural': '05. Medidores',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '06. Notificação',
                'verbose_name_plural': '06. Notificações',
            },
        ),
        migrations.CreateModel(
            name='Patrimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '07. Patrimônio',
                'verbose_name_plural': '07. Patrimônios',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '10. Tarefa',
                'verbose_name_plural': '10. Tarefas',
            },
        ),
        migrations.CreateModel(
            name='VirtualAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '11. Assembleia Virtual',
                'verbose_name_plural': '11. Assembleias Virtuais',
            },
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(validators=[core.services.validators.validate_date], verbose_name='Data de Lançamento')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('circular_content', models.TextField(verbose_name='Conteúdo da Circular')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulars', to='condominium.condominium', verbose_name='Condomínio')),
                ('connection_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulars', to='email_service.connectionstatus', verbose_name='Status')),
                ('email_smtp_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='circulars', to='email_service.smtpconfiguration', verbose_name='Configuração SMTP')),
                ('residents', models.ManyToManyField(blank=True, related_name='circulars', to='residents.resident', verbose_name='Residentes')),
                ('types_residents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='circulars', to='parameters.residenttype', verbose_name='Tipo de Residente')),
            ],
            options={
                'verbose_name': '02. Circular',
                'verbose_name_plural': '02. Circulares',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compe', models.PositiveIntegerField(verbose_name='Cod. Banco')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Nome Banco')),
                ('account_type', models.CharField(choices=[('checking_account', 'Conta Corrente'), ('savings_account', 'Conta Poupança'), ('university_account', 'Conta Universitária'), ('digital_account', 'Conta Digital'), ('salary_account', 'Conta-Salário'), ('joint_account', 'Conta Conjunta'), ('business_account', 'Conta Empresarial'), ('international_account', 'Conta Internacional'), ('investment_account', 'Conta Investimento')], max_length=50, verbose_name='Tipo de Conta')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo Inicial')),
                ('initial_balance_date', models.DateField(blank=True, null=True, verbose_name='Data Saldo Inicial')),
                ('account_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Conta')),
                ('iban', models.CharField(blank=True, max_length=30, null=True, verbose_name='IBAN')),
                ('agency', models.CharField(max_length=10, verbose_name='Agência')),
                ('account_number', models.CharField(max_length=20, verbose_name='Número da Conta')),
                ('account_digit', models.CharField(max_length=2, verbose_name='Dígito da Conta')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('full_name_drawn', models.CharField(max_length=250, verbose_name='Nome Completo Sacado')),
                ('cpf_drawn', models.CharField(max_length=14, verbose_name='CPF Sacado')),
                ('rg_drawn', models.CharField(max_length=20, verbose_name='RG Sacado')),
                ('phone_drawn', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Sacado')),
                ('email_drawn', models.EmailField(max_length=254, verbose_name='Email Sacado')),
                ('full_name_manager', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome do Gerente')),
                ('phone1_manager', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1 Gerente')),
                ('phone2_manager', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2 Gerente')),
                ('phone3_manager', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 3 Gerente')),
                ('email_manager', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Gerente')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('addresses_drawn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawn_address', to='parameters.addresses', verbose_name='Endereço Sacado')),
                ('bank_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank', to='parameters.addresses', verbose_name='Endereço do Banco')),
                ('condominium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank', to='condominium.condominium', verbose_name='Condomínio Beneficiário')),
            ],
            options={
                'verbose_name': '01. Banco',
                'verbose_name_plural': '01. Bancos',
                'unique_together': {('compe', 'account_type', 'agency', 'account_number'), ('compe', 'agency', 'account_number', 'cpf_drawn')},
            },
        ),
        migrations.AddConstraint(
            model_name='circular',
            constraint=models.UniqueConstraint(fields=('condominium', 'release_date', 'title'), name='unique_circular_by_condominium_date_title'),
        ),
    ]
