# Generated by Django 5.0.3 on 2026-06-29 22:10

import core.services.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
        ('condominium', '0037_alter_types_collaborators_unique_together_and_more'),
        ('parameters', '0008_documenttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['title', 'created_at'], 'verbose_name': '03. Documento', 'verbose_name_plural': '03. Documentos'},
        ),
        migrations.AddField(
            model_name='documents',
            name='condominium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrative_documents', to='condominium.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='documents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='documents',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='parameters.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='documents',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='administrative/documents/', verbose_name='Arquivo do Documento'),
        ),
        migrations.AddField(
            model_name='documents',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='documents',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='documents',
            name='registration_date',
            field=models.DateField(blank=True, null=True, validators=[core.services.validators.validate_date], verbose_name='Data de Registro'),
        ),
        migrations.AddField(
            model_name='documents',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Documento'),
        ),
        migrations.AddField(
            model_name='documents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterUniqueTogether(
            name='documents',
            unique_together={('condominium', 'title', 'registration_date')},
        ),
        migrations.AlterModelTable(
            name='documents',
            table='administrative_document',
        ),
    ]
