# Generated by Django 5.0.3 on 2026-05-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': '01. Banco', 'verbose_name_plural': '01. Bancos'},
        ),
        migrations.AlterModelOptions(
            name='budgetforecast',
            options={'verbose_name': '08. Previsão Orçamentária', 'verbose_name_plural': '08. Previsões Orçamentárias'},
        ),
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'verbose_name': '09. Plano de Conta', 'verbose_name_plural': '09. Plano de Contas'},
        ),
        migrations.AlterModelOptions(
            name='circular',
            options={'verbose_name': '02. Circular', 'verbose_name_plural': '02. Circulares'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '03. Contrato', 'verbose_name_plural': '03. Contratos'},
        ),
        migrations.AlterModelOptions(
            name='infraction',
            options={'verbose_name': '04. Infração', 'verbose_name_plural': '04. Infrações'},
        ),
        migrations.AlterModelOptions(
            name='meter',
            options={'verbose_name': '05. Medidor', 'verbose_name_plural': '05. Medidores'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '06. Notificação', 'verbose_name_plural': '06. Notificações'},
        ),
        migrations.AlterModelOptions(
            name='patrimony',
            options={'verbose_name': '07. Patrimônio', 'verbose_name_plural': '07. Patrimônios'},
        ),
    ]
