# Generated by Django 5.0.3 on 2026-05-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_alter_bank_options_alter_budgetforecast_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '12. Assembleia Virtual',
                'verbose_name_plural': '12. Assembleias Virtuais',
            },
        ),
    ]
