# Generated by Django 5.0.3 on 2026-07-01 18:39

import django.db.models.deletion
import domains.administrative.validators.validators
import shared.validators.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_alter_documents_options_documents_condominium_and_more'),
        ('email_service', '0014_alter_shippingqueue_uuid_and_more'),
        ('parameters', '0010_infractionstype_infraction_type'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infraction',
            options={'ordering': ['-releaseDate', 'title'], 'verbose_name': '04. Infração', 'verbose_name_plural': '04. Infrações'},
        ),
        migrations.AddField(
            model_name='infraction',
            name='condominium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='residents.condominiumunit', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='connection_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_service.connectionstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='email_SMTPConfiguration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infractions', to='email_service.smtpconfiguration', verbose_name='Configuração SMTP'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='administrative/infractions/', validators=[domains.administrative.validators.validators.validate_infraction_file_extension], verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='infractionContent',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo da Infração'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='infractions_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='parameters.infractionstype', verbose_name='Tipo de Infração'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='releaseDate',
            field=models.DateField(blank=True, null=True, validators=[shared.validators.common.validate_date], verbose_name='Data de Lançamento'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='residents',
            field=models.ManyToManyField(blank=True, related_name='infractions', to='residents.resident', verbose_name='Residentes'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='typesResidents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infraction_resident_types', to='parameters.residenttype', verbose_name='Tipo de Residente'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddIndex(
            model_name='infraction',
            index=models.Index(fields=['releaseDate'], name='administrat_release_203faf_idx'),
        ),
        migrations.AddIndex(
            model_name='infraction',
            index=models.Index(fields=['is_active'], name='administrat_is_acti_989a35_idx'),
        ),
        migrations.AddIndex(
            model_name='infraction',
            index=models.Index(fields=['created_at'], name='administrat_created_61a803_idx'),
        ),
    ]
