# Generated by Django 5.0.3 on 2026-07-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0003_alter_infraction_options_infraction_condominium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraction',
            name='email_SMTPConfiguration',
        ),
    ]
