# Generated by Django 5.0.3 on 2026-07-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0004_remove_infraction_email_smtpconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraction',
            name='residents',
        ),
        migrations.RemoveField(
            model_name='infraction',
            name='typesResidents',
        ),
    ]
