# Generated by Django 5.0.3 on 2026-05-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0004_alter_bank_options_alter_budgetforecast_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='compe',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cod Banco'),
        ),
    ]
