# Generated by Django 5.0.3 on 2026-07-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0005_remove_infraction_residents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraction',
            name='connection_status',
        ),
    ]
