# Generated by Django 5.0.3 on 2026-07-02 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0006_remove_infraction_connection_status'),
        ('email_service', '0014_alter_shippingqueue_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraction',
            name='connection_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_service.connectionstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='email_smtp_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infractions', to='email_service.smtpconfiguration', verbose_name='Configuração SMTP'),
        ),
    ]
