# Generated by Django 5.0.3 on 2026-07-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0007_infraction_connection_status_and_more'),
        ('email_service', '0014_alter_shippingqueue_uuid_and_more'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='circular',
            name='unique_circular_by_condominium_date_title',
        ),
        migrations.RemoveField(
            model_name='circular',
            name='residents',
        ),
        migrations.RemoveField(
            model_name='circular',
            name='types_residents',
        ),
        migrations.RemoveField(
            model_name='circular',
            name='condominium',
        ),
        migrations.RemoveField(
            model_name='infraction',
            name='condominium',
        ),
        migrations.AddConstraint(
            model_name='circular',
            constraint=models.UniqueConstraint(fields=('release_date', 'title'), name='unique_circular_by_date_title'),
        ),
        migrations.AddField(
            model_name='circular',
            name='condominium',
            field=models.ManyToManyField(blank=True, related_name='circulars', to='residents.condominiumunit', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='condominium',
            field=models.ManyToManyField(blank=True, related_name='infractions', to='residents.condominiumunit', verbose_name='Condomínio'),
        ),
    ]
