# Generated by Django 5.0.3 on 2026-05-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0008_alter_bank_initial_balance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_digit',
            field=models.IntegerField(default='99999', max_length=5, verbose_name='Dígito da Conta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.CharField(default=99999, max_length=20, verbose_name='Número da Conta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('checking_account', 'Conta Corrente'), ('savings_account', 'Conta Poupança'), ('university_account', 'Conta Universitária'), ('digital_account', 'Conta Digital'), ('salary_account', 'Conta-Salário'), ('joint_account', 'Conta Conjunta'), ('business_account', 'Conta Empresarial'), ('international_account', 'Conta Internacional'), ('investment_account', 'Conta Investimento')], default='Conta Empresarial', max_length=50, verbose_name='Tipo de Conta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='agency',
            field=models.CharField(default='0900', max_length=10, verbose_name='Agência'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(default='Banco Itau', max_length=255, verbose_name='Nome Banco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='compe',
            field=models.PositiveIntegerField(default='341', max_length=5, verbose_name='Cod. Banco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='cpf_drawn',
            field=models.CharField(default='09876523309', max_length=14, verbose_name='CPF Sacado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='email_drawn',
            field=models.EmailField(default='underboy@mail.com', max_length=254, verbose_name='Email Sacado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='full_name_drawn',
            field=models.CharField(default='Ana Castela', max_length=250, verbose_name='Nome Completo Sacado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo Inicial'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='rg_drawn',
            field=models.CharField(max_length=20, verbose_name='RG Sacado'),
        ),
    ]
