# Generated by Django 5.0.3 on 2026-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0008_remove_circular_unique_circular_by_condominium_date_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='logs',
            field=models.TextField(blank=True, null=True, verbose_name='Logs'),
        ),
    ]
