# Generated by Django 5.0.3 on 2026-07-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0009_circular_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraction',
            name='logs',
            field=models.TextField(blank=True, null=True, verbose_name='Logs'),
        ),
    ]
