# Generated by Django 5.0.3 on 2026-05-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0010_alter_bank_account_digit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract',
            new_name='Documents',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': '01. Banco', 'verbose_name_plural': '01. Bancos'},
        ),
        migrations.AlterModelOptions(
            name='budgetforecast',
            options={'verbose_name': '08. Previsão Orçamentária', 'verbose_name_plural': '08. Previsões Orçamentárias'},
        ),
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'verbose_name': '09. Plano de Conta', 'verbose_name_plural': '09. Plano de Contas'},
        ),
        migrations.AlterModelOptions(
            name='circular',
            options={'verbose_name': '02. Circular', 'verbose_name_plural': '02. Circulares'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': '03. Documento', 'verbose_name_plural': '03. Documentos'},
        ),
        migrations.AlterModelOptions(
            name='infraction',
            options={'verbose_name': '04. Infração', 'verbose_name_plural': '04. Infrações'},
        ),
        migrations.AlterModelOptions(
            name='meter',
            options={'verbose_name': '05. Medidor', 'verbose_name_plural': '05. Medidores'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '06. Notificação', 'verbose_name_plural': '06. Notificações'},
        ),
        migrations.AlterModelOptions(
            name='patrimony',
            options={'verbose_name': '07. Patrimônio', 'verbose_name_plural': '07. Patrimônios'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '10. Tarefa', 'verbose_name_plural': '10. Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='virtualassembly',
            options={'verbose_name': '11. Assembleia Virtual', 'verbose_name_plural': '11. Assembleias Virtuais'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='compe',
            field=models.PositiveIntegerField(verbose_name='Cod. Banco'),
        ),
    ]
