# Generated by Django 5.0.3 on 2026-07-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0011_circular_types_residents'),
        ('parameters', '0010_infractionstype_infraction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraction',
            name='types_residents',
            field=models.ManyToManyField(blank=True, related_name='infractions', to='parameters.residenttype', verbose_name='Tipos de Residentes'),
        ),
    ]
