# Generated by Django 5.0.3 on 2026-07-04 14:40

import core.services.validators
import django.db.models.deletion
import domains.administrative.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0012_infraction_types_residents'),
        ('parameters', '0011_metertype'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releaseDate', models.DateField(blank=True, null=True, validators=[core.services.validators.validate_date], verbose_name='Data de Lançamento')),
                ('composition', models.CharField(help_text='Informe a competência no formato MM/AAAA.', max_length=10, validators=[domains.administrative.validators.validators.validate_meter_composition], verbose_name='Composição')),
                ('previousValue', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Valor Anterior')),
                ('currentValue', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Valor Atual')),
                ('Consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Consumo')),
                ('Value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor')),
                ('file', models.FileField(upload_to='administrative/documents/', validators=[domains.administrative.validators.validators.validate_meter_file_extension], verbose_name='Arquivo do Documento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_condominium_records', to='residents.condominiumunit', verbose_name='Condomínio')),
                ('meterType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='parameters.metertype', verbose_name='Tipo de Medidor')),
                ('unit_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_unit_records', to='residents.condominiumunit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': '05. Medidor',
                'verbose_name_plural': '05. Medidores',
                'ordering': ['-releaseDate', 'composition'],
                'indexes': [models.Index(fields=['releaseDate'], name='administrat_release_1d96b7_idx'), models.Index(fields=['composition'], name='administrat_composi_79ac44_idx'), models.Index(fields=['is_active'], name='administrat_is_acti_c85097_idx'), models.Index(fields=['created_at'], name='administrat_created_c67c64_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='meters',
            constraint=models.UniqueConstraint(fields=('condominium', 'unit_identification', 'meterType', 'composition'), name='unique_meter_condominium_unit_type_composition'),
        ),
    ]
