# Generated by Django 5.0.3 on 2026-07-04 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0013_meters_and_more'),
        ('parameters', '0013_alter_metertype_description'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meters',
            name='unique_meter_condominium_unit_type_composition',
        ),
        migrations.RemoveField(
            model_name='meters',
            name='unit_identification',
        ),
        migrations.AlterField(
            model_name='meters',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_records', to='residents.condominiumunit', verbose_name='Condomínio/Unidade'),
        ),
        migrations.AddConstraint(
            model_name='meters',
            constraint=models.UniqueConstraint(fields=('condominium', 'meterType', 'composition'), name='unique_meter_condominium_type_composition'),
        ),
    ]
