# Generated by Django 5.0.3 on 2026-07-04 16:39

import domains.administrative.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0014_remove_meters_unique_meter_condominium_unit_type_composition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='administrative/documents/', validators=[domains.administrative.validators.validators.validate_meter_file_extension], verbose_name='Arquivo do Documento'),
        ),
    ]
