# Generated by Django 5.0.3 on 2026-07-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0015_alter_meters_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
