# Generated by Django 5.0.3 on 2026-07-17 14:30

import core.services.validators
import django.core.validators
import django.db.models.deletion
import domains.administrative.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0016_delete_notification'),
        ('condominium', '0037_alter_types_collaborators_unique_together_and_more'),
        ('parameters', '0014_assetbrand_assetcategory_assetmaintenancefrequency_and_more'),
        ('personalities', '0011_alter_businesssector_table_alter_entity_table'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetforecast',
            options={'verbose_name': '07. Previsão Orçamentária', 'verbose_name_plural': '07. Previsões Orçamentárias'},
        ),
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'verbose_name': '08. Plano de Conta', 'verbose_name_plural': '08. Plano de Contas'},
        ),
        migrations.AlterModelOptions(
            name='patrimony',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': '06. Patrimônio', 'verbose_name_plural': '06. Patrimônios'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '09. Tarefa', 'verbose_name_plural': '09. Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='virtualassembly',
            options={'verbose_name': '10. Assembleia Virtual', 'verbose_name_plural': '10. Assembleias Virtuais'},
        ),
        migrations.AddField(
            model_name='patrimony',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='asset_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonies_by_brand', to='parameters.assetbrand', verbose_name='Marca do Patrimônio'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonies_by_category', to='parameters.assetcategory', verbose_name='Categoria de Patrimônio'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='asset_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código do Patrimônio'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='asset_model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='asset_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonies_by_status', to='parameters.assetstatus', verbose_name='Status do Patrimônio'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonies_by_type', to='parameters.assettype', verbose_name='Tipo de Patrimônio'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='condominium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patrimonies', to='residents.condominiumunit', verbose_name='Condomínio/Unidade'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Atual'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taxa de Depreciação'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='administrative/patrimonys/', validators=[domains.administrative.validators.validators.validate_file_size_10mb, domains.administrative.validators.validators.validate_invoice_extension], verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última Manutenção'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='administrative/patrimonys/', validators=[domains.administrative.validators.validators.validate_file_size_10mb, domains.administrative.validators.validators.validate_photo_extension], verbose_name='Foto Principal'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='maintenance_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonies_by_frequency', to='parameters.assetmaintenancefrequency', verbose_name='Frequência de Manutenção'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='maintenance_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações de Manutenção'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='manual_file',
            field=models.FileField(blank=True, null=True, upload_to='administrative/patrimonys/', validators=[domains.administrative.validators.validators.validate_file_size_10mb, domains.administrative.validators.validators.validate_manual_extension], verbose_name='Manual Técnico'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Patrimônio'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Manutenção'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor de Compra'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='release_date',
            field=models.DateField(blank=True, null=True, validators=[core.services.validators.validate_date], verbose_name='Data de Lançamento'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='requires_maintenance',
            field=models.BooleanField(default=False, verbose_name='Requer Manutenção'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonies_by_responsible', to='condominium.collaborator', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='serial_number',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Número de Série'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='state_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonies_by_condition', to='parameters.assetstatecondition', verbose_name='Estado de Conservação'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonies_by_supplier', to='personalities.entity', verbose_name='Entidades'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='useful_life_months',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Vida Útil em Meses'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='warranty_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da Garantia'),
        ),
        migrations.AddField(
            model_name='patrimony',
            name='warranty_file',
            field=models.FileField(blank=True, null=True, upload_to='administrative/patrimonys/', validators=[domains.administrative.validators.validators.validate_file_size_10mb, domains.administrative.validators.validators.validate_warranty_extension], verbose_name='Certificado de Garantia'),
        ),
        migrations.AddIndex(
            model_name='patrimony',
            index=models.Index(fields=['asset_code'], name='administrat_asset_c_1d906e_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimony',
            index=models.Index(fields=['name'], name='administrat_name_75eabf_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimony',
            index=models.Index(fields=['is_active'], name='administrat_is_acti_194459_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimony',
            index=models.Index(fields=['release_date'], name='administrat_release_9e664c_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimony',
            index=models.Index(fields=['acquisition_date'], name='administrat_acquisi_95203c_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimony',
            index=models.Index(fields=['asset_status'], name='administrat_asset_s_3eed9f_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimony',
            index=models.Index(fields=['asset_type'], name='administrat_asset_t_9a1885_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimony',
            index=models.Index(fields=['asset_category'], name='administrat_asset_c_e8b4fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='patrimony',
            constraint=models.UniqueConstraint(fields=('asset_code',), name='unique_patrimony_asset_code'),
        ),
    ]
