# Generated by Django 5.0.3 on 2026-07-17 14:31

import core.services.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0017_alter_budgetforecast_options_and_more'),
        ('parameters', '0014_assetbrand_assetcategory_assetmaintenancefrequency_and_more'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimony',
            name='acquisition_date',
            field=models.DateField(verbose_name='Data de Aquisição'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='asset_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonies_by_category', to='parameters.assetcategory', verbose_name='Categoria de Patrimônio'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='asset_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonies_by_status', to='parameters.assetstatus', verbose_name='Status do Patrimônio'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonies_by_type', to='parameters.assettype', verbose_name='Tipo de Patrimônio'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonies', to='residents.condominiumunit', verbose_name='Condomínio/Unidade'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome do Patrimônio'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='release_date',
            field=models.DateField(validators=[core.services.validators.validate_date], verbose_name='Data de Lançamento'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='state_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonies_by_condition', to='parameters.assetstatecondition', verbose_name='Estado de Conservação'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
