# Generated by Django 5.0.3 on 2026-07-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0018_alter_patrimony_acquisition_date_and_more'),
        ('condominium', '0037_alter_types_collaborators_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimony',
            name='condominium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonies', to='condominium.condominium', verbose_name='Condomínio'),
        ),
    ]
