# Generated by Django 5.0.3 on 2026-07-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0019_alter_patrimony_condominium'),
        ('condominium', '0037_alter_types_collaborators_unique_together_and_more'),
        ('parameters', '0015_bankaccounttype_alter_assetbrand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetforecast',
            options={'verbose_name': '08. Previsão Orçamentária', 'verbose_name_plural': '08. Previsões Orçamentárias'},
        ),
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'verbose_name': '09. Plano de Conta', 'verbose_name_plural': '09. Plano de Contas'},
        ),
        migrations.AlterModelOptions(
            name='circular',
            options={'ordering': ['-release_date', '-created_at'], 'verbose_name': '03. Circular', 'verbose_name_plural': '03. Circulares'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['title', 'created_at'], 'verbose_name': '04. Documento', 'verbose_name_plural': '04. Documentos'},
        ),
        migrations.AlterModelOptions(
            name='infraction',
            options={'ordering': ['-releaseDate', 'title'], 'verbose_name': '05. Infração', 'verbose_name_plural': '05. Infrações'},
        ),
        migrations.AlterModelOptions(
            name='meters',
            options={'ordering': ['-releaseDate', 'composition'], 'verbose_name': '06. Medidor', 'verbose_name_plural': '06. Medidores'},
        ),
        migrations.AlterModelOptions(
            name='patrimony',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': '07. Patrimônio', 'verbose_name_plural': '07. Patrimônios'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '10. Tarefa', 'verbose_name_plural': '10. Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='virtualassembly',
            options={'verbose_name': '11. Assembleia Virtual', 'verbose_name_plural': '11. Assembleias Virtuais'},
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Saldo Inicial')),
                ('initial_balance_date', models.DateField(verbose_name='Data do Saldo Inicial')),
                ('account_name', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('agency', models.CharField(max_length=6, verbose_name='Agência')),
                ('account_number', models.CharField(max_length=20, verbose_name='Número da Conta')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='parameters.bankaccounttype', verbose_name='Tipo de Conta')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='administrative.bank', verbose_name='Banco')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='condominium.condominium', verbose_name='Condomínio')),
            ],
            options={
                'verbose_name': '02. Conta Bancária',
                'verbose_name_plural': '02. Contas Bancárias',
                'db_table': 'administrative_bankaccount',
                'ordering': ['account_name'],
                'indexes': [models.Index(fields=['is_active'], name='administrat_is_acti_71511b_idx'), models.Index(fields=['bank', 'condominium'], name='administrat_bank_id_4fe7e9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('bank', 'condominium', 'account_type', 'agency'), name='uq_bank_account_bank_condominium_type_agency'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('bank', 'agency', 'account_number'), name='uq_bank_account_bank_agency_number'),
        ),
    ]
