# Generated by Django 5.0.3 on 2026-07-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0020_alter_budgetforecast_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_digit',
            field=models.CharField(default='', max_length=3, verbose_name='Dígito da Conta'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='compe',
            field=models.PositiveIntegerField(unique=True, verbose_name='Cod. Banco'),
        ),
        migrations.RemoveField(
            model_name='bank',
            name='account_digit',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='addresses_drawn',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='condominium',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='cpf_drawn',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='email_drawn',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='full_name_drawn',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='initial_balance',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='initial_balance_date',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='phone_drawn',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='rg_drawn',
        ),
    ]
