# Generated by Django 5.0.3 on 2026-07-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0022_chartofaccount_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='administrat_condomi_9565a2_idx',
            old_name='administrat_condomi_0f5430_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='administrat_condomi_b98069_idx',
            old_name='administrat_condomi_06f3f3_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='administrat_condomi_e86c6b_idx',
            old_name='administrat_condomi_cb76f2_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='administrat_condomi_2ce60a_idx',
            old_name='administrat_condomi_ec7037_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='administrat_account_428f78_idx',
            old_name='administrat_account_94b8ac_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='administrat_account_b67ba3_idx',
            old_name='administrat_account_20c0cf_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='administrat_effecti_0e8271_idx',
            old_name='administrat_effecti_8a803a_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='administrat_effecti_e2d72c_idx',
            old_name='administrat_effecti_26a54b_idx',
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_accounts', to='administrative.chartofaccount', verbose_name='Conta-pai'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='replacement_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_replaced', to='administrative.chartofaccount', verbose_name='Conta substituta'),
        ),
    ]
