# Generated by Django 5.0.3 on 2026-07-30 17:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0023_rename_administrat_condomi_0f5430_idx_administrat_condomi_9565a2_idx_and_more'),
        ('condominium', '0038_alter_collaborator_name_alter_condominium_is_active_and_more'),
        ('email_service', '0014_alter_shippingqueue_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': '10. Tarefa', 'verbose_name_plural': '10. Tarefas'},
        ),
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de conclusao'),
        ),
        migrations.AddField(
            model_name='task',
            name='condominium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='condominium.condominium', verbose_name='Condominio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2026, 7, 30), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='Default description', verbose_name='Descricao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_completion_date',
            field=models.DateField(default=datetime.date(2026, 7, 30), verbose_name='Data prevista de conclusao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='task',
            name='release_date',
            field=models.DateField(default=datetime.date(2026, 7, 30), verbose_name='Data de lancamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='email_service.connectionstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='default-title', max_length=255, verbose_name='Titulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['condominium', 'is_active'], name='administrat_condomi_1a8492_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['responsible_user'], name='administrat_respons_e267e2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='administrat_status__b9e652_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['release_date'], name='administrat_release_03e4f5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['estimated_completion_date'], name='administrat_estimat_7042d5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completion_date'], name='administrat_complet_4982ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('condominium', 'title'), name='uq_task_condominium_title'),
        ),
        migrations.AlterModelTable(
            name='task',
            table='administrative_task',
        ),
    ]
