# Generated by Django 5.0.3 on 2026-07-30 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0024_alter_task_options_task_completion_date_and_more'),
        ('condominium', '0038_alter_collaborator_name_alter_condominium_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de conclusão'),
        ),
        migrations.AlterField(
            model_name='task',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='condominium.condominium', verbose_name='Condomínio'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_completion_date',
            field=models.DateField(verbose_name='Data prevista de conclusão'),
        ),
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.DateField(verbose_name='Data de lançamento'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_date', models.DateField(verbose_name='Data do histórico')),
                ('description_history', models.TextField(verbose_name='Descrição do histórico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_histories', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='administrative.task', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Histórico da Tarefa',
                'verbose_name_plural': 'Históricos da Tarefa',
                'db_table': 'administrative_task_history',
                'ordering': ['-history_date', '-created_at'],
                'indexes': [models.Index(fields=['task', 'history_date'], name='administrat_task_id_69c11f_idx'), models.Index(fields=['created_by_user'], name='administrat_created_31271c_idx')],
            },
        ),
    ]
