# Generated by Django 5.0.3 on 2026-08-10 17:01

import django.db.models.deletion
import domains.administrative.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0025_alter_task_completion_date_alter_task_condominium_and_more'),
        ('condominium', '0038_alter_collaborator_name_alter_condominium_is_active_and_more'),
        ('parameters', '0031_topicoption'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('location', models.CharField(blank=True, max_length=250, verbose_name='Local')),
                ('meeting_date_time_start', models.DateTimeField(verbose_name='Início da assembleia')),
                ('meeting_date_time_end', models.DateTimeField(verbose_name='Término da assembleia')),
                ('meeting_date_time_voting_begins', models.DateTimeField(verbose_name='Início da votação')),
                ('meeting_date_time_voting_end', models.DateTimeField(verbose_name='Término da votação')),
                ('president', models.CharField(max_length=250, verbose_name='Presidente')),
                ('secretary', models.CharField(max_length=250, verbose_name='Secretário')),
                ('video_conference_link', models.URLField(blank=True, max_length=250, verbose_name='Link da videoconferência')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('notice_meeting_date_time', models.DateTimeField(verbose_name='Data da convocação')),
                ('notice_meeting_description', models.TextField(blank=True, verbose_name='Descrição do edital')),
                ('notice_meeting_send_email_participants', models.BooleanField(default=False, verbose_name='Enviar e-mail aos participantes')),
                ('ban_those_in_default_from_voting', models.BooleanField(default=False, verbose_name='Impedir inadimplentes de votar')),
                ('hide_results_from_participants_during_voting', models.BooleanField(default=False, verbose_name='Ocultar resultados durante a votação')),
                ('release_the_agenda_for_vote', models.BooleanField(default=False, verbose_name='Liberar a pauta para votação')),
                ('allow_comments', models.BooleanField(default=False, verbose_name='Permitir comentários')),
                ('show_comments', models.BooleanField(default=False, verbose_name='Exibir comentários')),
                ('allow_replies_to_comments', models.BooleanField(default=False, verbose_name='Permitir respostas aos comentários')),
                ('show_replies_to_comments', models.BooleanField(default=False, verbose_name='Exibir respostas aos comentários')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_meetings', to='condominium.condominium', verbose_name='Condomínio')),
                ('meeting_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_meetings', to='parameters.assemblystatus', verbose_name='Status da assembleia')),
                ('participating_groups', models.ManyToManyField(blank=True, related_name='virtual_meetings', to='parameters.residenttype', verbose_name='Grupos participantes')),
                ('voting_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_meetings', to='parameters.votingtype', verbose_name='Tipo de Votação')),
            ],
            options={
                'verbose_name': '11. Assembleia Virtual',
                'verbose_name_plural': '11. Assembleias Virtuais',
                'db_table': 'administrative_virtualmeeting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualMeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_meeting_participants', to='residents.resident', verbose_name='Morador')),
                ('resident_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_meeting_participants', to='parameters.residenttype', verbose_name='Tipo de Residente')),
                ('virtual_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='administrative.virtualmeeting', verbose_name='Assembleia')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'db_table': 'administrative_virtualmeetingparticipant',
                'ordering': ['resident__name'],
            },
        ),
        migrations.CreateModel(
            name='VirtualMeetingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('topic_options', models.ManyToManyField(blank=True, related_name='virtual_meeting_topics', to='parameters.topicoption', verbose_name='Opções de votação')),
                ('virtual_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='administrative.virtualmeeting', verbose_name='Assembleia')),
            ],
            options={
                'verbose_name': 'Pauta',
                'verbose_name_plural': 'Pautas',
                'db_table': 'administrative_virtualmeetingtopic',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VirtualMeetingTopicAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='administrative/virtual_meetings/topics/', validators=[domains.administrative.validators.validators.validate_topic_attachment_extension, domains.administrative.validators.validators.validate_file_size_10mb], verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='administrative.virtualmeetingtopic', verbose_name='Pauta')),
            ],
            options={
                'verbose_name': 'Anexo da Pauta',
                'verbose_name_plural': 'Anexos das Pautas',
                'db_table': 'administrative_virtualmeetingtopicattachment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='VirtualAssembly',
        ),
        migrations.AddIndex(
            model_name='virtualmeeting',
            index=models.Index(fields=['condominium'], name='administrat_condomi_9b09f1_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmeeting',
            index=models.Index(fields=['meeting_status'], name='administrat_meeting_dc40fe_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmeeting',
            index=models.Index(fields=['meeting_date_time_start'], name='administrat_meeting_e9e924_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmeeting',
            index=models.Index(fields=['meeting_date_time_end'], name='administrat_meeting_b99df0_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmeeting',
            index=models.Index(fields=['notice_meeting_date_time'], name='administrat_notice__1173ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='virtualmeeting',
            constraint=models.CheckConstraint(check=models.Q(('meeting_date_time_end__gt', models.F('meeting_date_time_start'))), name='check_meeting_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='virtualmeeting',
            constraint=models.CheckConstraint(check=models.Q(('meeting_date_time_voting_end__gt', models.F('meeting_date_time_voting_begins'))), name='check_voting_end_after_begins'),
        ),
        migrations.AddConstraint(
            model_name='virtualmeeting',
            constraint=models.CheckConstraint(check=models.Q(('notice_meeting_date_time__lt', models.F('meeting_date_time_start'))), name='check_notice_before_start'),
        ),
        migrations.AddIndex(
            model_name='virtualmeetingparticipant',
            index=models.Index(fields=['virtual_meeting'], name='administrat_virtual_cfe317_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmeetingparticipant',
            index=models.Index(fields=['resident'], name='administrat_residen_2cc62c_idx'),
        ),
        migrations.AddConstraint(
            model_name='virtualmeetingparticipant',
            constraint=models.UniqueConstraint(fields=('virtual_meeting', 'resident'), name='unique_resident_per_virtual_meeting'),
        ),
        migrations.AddIndex(
            model_name='virtualmeetingtopic',
            index=models.Index(fields=['virtual_meeting'], name='administrat_virtual_16ff60_idx'),
        ),
        migrations.AddConstraint(
            model_name='virtualmeetingtopic',
            constraint=models.UniqueConstraint(fields=('virtual_meeting', 'title'), name='unique_topic_title_per_virtual_meeting'),
        ),
        migrations.AddIndex(
            model_name='virtualmeetingtopicattachment',
            index=models.Index(fields=['topic'], name='administrat_topic_i_b2acb9_idx'),
        ),
    ]
