# Generated by Django 5.0.3 on 2026-08-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0026_virtualmeeting_virtualmeetingparticipant_and_more'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmeeting',
            name='participating_resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Resident', to='residents.resident', verbose_name='Participantes'),
        ),
        migrations.AddField(
            model_name='virtualmeeting',
            name='participating_vote_unit',
            field=models.BooleanField(default=False, verbose_name='Voto principal por unidade?'),
        ),
    ]
