# Generated by Django 5.0.3 on 2026-08-11 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0028_remove_virtualmeeting_participating_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmeeting',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_virtual_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
