# Generated by Django 5.0.3 on 2026-08-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0029_virtualmeeting_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmeeting',
            name='ban_those_in_default_from_voting',
            field=models.BooleanField(default=True, verbose_name='Impedir inadimplentes de votar'),
        ),
        migrations.AlterField(
            model_name='virtualmeeting',
            name='hide_results_from_participants_during_voting',
            field=models.BooleanField(default=True, verbose_name='Ocultar resultados durante a votação'),
        ),
        migrations.AlterField(
            model_name='virtualmeeting',
            name='participating_vote_unit',
            field=models.BooleanField(default=True, verbose_name='Voto principal por unidade?'),
        ),
        migrations.AlterField(
            model_name='virtualmeeting',
            name='release_the_agenda_for_vote',
            field=models.BooleanField(default=True, verbose_name='Liberar a pauta para votação'),
        ),
    ]
