# Generated by Django 5.0.3 on 2026-08-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0030_alter_virtualmeeting_ban_those_in_default_from_voting_and_more'),
        ('parameters', '0031_topicoption'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualmeeting',
            options={'ordering': ['-created_at'], 'verbose_name': '11. Votação Virtual', 'verbose_name_plural': '11. Votações Virtuais'},
        ),
        migrations.RemoveField(
            model_name='virtualmeeting',
            name='participating_groups',
        ),
        migrations.RemoveField(
            model_name='virtualmeeting',
            name='participating_resident',
        ),
        migrations.AddField(
            model_name='virtualmeeting',
            name='participating_groups',
            field=models.ManyToManyField(blank=True, related_name='virtual_meetings', to='parameters.residenttype', verbose_name='Grupos participantes'),
        ),
        migrations.AddField(
            model_name='virtualmeeting',
            name='participating_resident',
            field=models.ManyToManyField(blank=True, related_name='virtual_meetings_residents', to='residents.resident', verbose_name='Participantes'),
        ),
    ]
