# Generated by Django 5.0.3 on 2026-08-11 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0031_alter_virtualmeeting_options_and_more'),
        ('parameters', '0031_topicoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmeeting',
            name='participating_groups',
        ),
        migrations.AddField(
            model_name='virtualmeeting',
            name='participating_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_meetings', to='parameters.residenttype', verbose_name='Grupos participantes'),
        ),
    ]
