# Generated by Django 5.0.3 on 2026-08-12 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0032_remove_virtualmeeting_participating_groups_and_more'),
        ('email_service', '0014_alter_shippingqueue_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmeeting',
            name='connection_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_meetings', to='email_service.connectionstatus', verbose_name='Email Status'),
        ),
        migrations.AddField(
            model_name='virtualmeeting',
            name='email_log',
            field=models.TextField(blank=True, default='', help_text='Histórico de registro dos envios de e-mails (somente leitura).', verbose_name='Email Logs'),
        ),
        migrations.AddField(
            model_name='virtualmeeting',
            name='email_smtp_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_meetings', to='email_service.smtpconfiguration', verbose_name='Configuração SMTP'),
        ),
    ]
