# Generated by Django 5.0.3 on 2026-08-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0033_virtualmeeting_connection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmeeting',
            name='notice_meeting_title',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Título do Edital de Convocação'),
        ),
    ]
