# Generated by Django 5.0.3 on 2026-08-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0034_virtualmeeting_notice_meeting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmeeting',
            name='notice_meeting_send_email_participants',
            field=models.BooleanField(default=True, verbose_name='Enviar e-mail aos participantes'),
        ),
    ]
