# Generated by Django 5.0.3 on 2026-08-12 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0035_alter_virtualmeeting_notice_meeting_send_email_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmeeting',
            name='meeting_date_time_send_mail',
            field=models.DateField(default=datetime.date(2025, 1, 1), verbose_name='Data/Hora da Assembléia - Envio do E-mail'),
            preserve_default=False,
        ),
    ]
