# Generated by Django 5.0.3 on 2026-08-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0036_virtualmeeting_meeting_date_time_send_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmeeting',
            name='meeting_date_time_send_mail',
            field=models.DateTimeField(verbose_name='Data/Hora - Envio do E-mail'),
        ),
    ]
