# Generated by Django 5.0.3 on 2026-08-12 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0037_alter_virtualmeeting_meeting_date_time_send_mail'),
        ('residents', '0048_alter_resident_options_alter_resident_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMeetingEmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('notice', 'Edital de Convocação'), ('voting', 'Convocação para Votação')], max_length=20, verbose_name='Tipo de e-mail')),
                ('scheduled_at', models.DateTimeField(verbose_name='Agendado para')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Último erro')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID da tarefa Celery')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('virtual_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_schedules', to='administrative.virtualmeeting', verbose_name='Votação Virtual')),
            ],
            options={
                'verbose_name': 'Agendamento de E-mail (Votação Virtual)',
                'verbose_name_plural': 'Agendamentos de E-mail (Votações Virtuais)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualMeetingEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Último erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_meeting_email_recipients', to='residents.resident', verbose_name='Morador')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='administrative.virtualmeetingemailschedule', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'Destinatário de E-mail (Votação Virtual)',
                'verbose_name_plural': 'Destinatários de E-mail (Votações Virtuais)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='virtualmeetingemailschedule',
            constraint=models.UniqueConstraint(fields=('virtual_meeting', 'email_type'), name='unique_virtual_meeting_email_schedule_type'),
        ),
        migrations.AddConstraint(
            model_name='virtualmeetingemailrecipient',
            constraint=models.UniqueConstraint(fields=('schedule', 'resident'), name='unique_virtual_meeting_email_recipient'),
        ),
    ]
