# Generated by Django 5.0.3 on 2026-05-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='active',
        ),
        migrations.RemoveField(
            model_name='circular',
            name='active',
        ),
        migrations.RemoveField(
            model_name='correspondence',
            name='active',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
        migrations.RemoveField(
            model_name='servicetransition',
            name='active',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='active',
        ),
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
        migrations.RemoveField(
            model_name='usefulphonenumber',
            name='active',
        ),
        migrations.RemoveField(
            model_name='visitorsregister',
            name='active',
        ),
    ]
