# Generated by Django 5.0.3 on 2026-05-18 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0002_remove_bag_active_remove_circular_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Circular',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterModelOptions(
            name='visitorsregister',
            options={'verbose_name': 'Reg. Visitante', 'verbose_name_plural': 'Reg. Visitantes'},
        ),
    ]
