# Generated by Django 5.0.3 on 2026-05-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatehouse', '0003_delete_circular_delete_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicTimeClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '9. Ponto Eletrônico',
                'verbose_name_plural': '9. Pontos Eletrônicos',
            },
        ),
        migrations.AlterModelOptions(
            name='bag',
            options={'verbose_name': '8. Malote', 'verbose_name_plural': '8. Malotes'},
        ),
        migrations.AlterModelOptions(
            name='correspondence',
            options={'verbose_name': '6. Correspondência', 'verbose_name_plural': '6. Correspondências'},
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'verbose_name': '7. Ocorrência', 'verbose_name_plural': '7. Ocorrências'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '4. Encomenda', 'verbose_name_plural': '4. Encomendas'},
        ),
        migrations.AlterModelOptions(
            name='servicetransition',
            options={'verbose_name': '2. Passagem de Serviço', 'verbose_name_plural': '2. Passagens de Serviços'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': '1. Plantão', 'verbose_name_plural': '1. Plantões'},
        ),
        migrations.AlterModelOptions(
            name='usefulphonenumber',
            options={'verbose_name': '3. Telefone Útil', 'verbose_name_plural': '3. Telefones Úteis'},
        ),
        migrations.AlterModelOptions(
            name='visitorsregister',
            options={'verbose_name': '5. Reg. Visitante', 'verbose_name_plural': '5. Reg. Visitantes'},
        ),
    ]
