# Generated by Django 5.0.3 on 2026-03-08 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('complement', models.CharField(max_length=255, verbose_name='Complemento')),
                ('city', models.CharField(max_length=100, verbose_name='Município')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('zip_code', models.CharField(max_length=20, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['country', 'state', 'city', 'street', 'number', 'complement'],
            },
        ),
        migrations.CreateModel(
            name='TypesCondominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tipo de Condomínio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Condomínio',
                'verbose_name_plural': 'Tipos de Condomínios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('state_registration', models.CharField(max_length=20, verbose_name='Inscrição Estadual')),
                ('municipal_registration', models.CharField(max_length=20, verbose_name='Inscrição Municipal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium', to='condominium.addresses', verbose_name='Endereço')),
                ('type_condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium', to='condominium.typescondominium', verbose_name='Tipo de Condomínio')),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
                'ordering': ['name', 'code', 'cnpj'],
            },
        ),
    ]
