# Generated by Django 5.0.3 on 2026-03-08 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0002_states_alter_addresses_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructionCondominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Estrutura do Condomínio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': '2. Estrutura do Condomínio',
                'verbose_name_plural': '2. Estruturas dos Condomínios',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ['country', 'state', 'city', 'street', 'number', 'complement'], 'verbose_name': '4. Endereço', 'verbose_name_plural': '4. Endereços'},
        ),
        migrations.AlterModelOptions(
            name='condominium',
            options={'ordering': ['name', 'code', 'cnpj'], 'verbose_name': '5. Condomínio', 'verbose_name_plural': '5. Condomínios'},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'ordering': ['abbreviation'], 'verbose_name': '3. Estado', 'verbose_name_plural': '3. Estados'},
        ),
        migrations.AddField(
            model_name='states',
            name='region',
            field=models.CharField(max_length=100, null=True, verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='condominium',
            name='struction_condominium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condominium', to='condominium.structioncondominium', verbose_name='Estrutura do Condomínio'),
        ),
    ]
