# Generated by Django 5.0.3 on 2026-03-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0004_states_capital_states_created_at_states_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='complement',
            field=models.CharField(max_length=255, verbose_name='Complemento'),
        ),
    ]
