# Generated by Django 5.0.3 on 2026-04-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0006_alter_addresses_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
    ]
