# Generated by Django 5.0.3 on 2026-04-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0007_addresses_neighborhood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ['country', 'state', 'city', 'street', 'number', 'complement', 'is_active', 'created_at'], 'verbose_name': '4. Endereço', 'verbose_name_plural': '4. Endereços'},
        ),
        migrations.AlterModelOptions(
            name='condominium',
            options={'ordering': ['name', 'code', 'cnpj', 'is_active', 'created_at'], 'verbose_name': '5. Condomínio', 'verbose_name_plural': '5. Condomínios'},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'ordering': ['abbreviation', 'name', 'region'], 'verbose_name': '3. Estado', 'verbose_name_plural': '3. Estados'},
        ),
        migrations.AlterModelOptions(
            name='structioncondominium',
            options={'ordering': ['name', 'is_active', 'created_at'], 'verbose_name': '2. Estrutura do Condomínio', 'verbose_name_plural': '2. Estruturas dos Condomínios'},
        ),
        migrations.AlterModelOptions(
            name='typescondominium',
            options={'ordering': ['name', 'is_active', 'created_at'], 'verbose_name': '1. Tipo de Condomínio', 'verbose_name_plural': '1. Tipos de Condomínios'},
        ),
    ]
