# Generated by Django 5.0.3 on 2026-04-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0008_alter_addresses_options_alter_condominium_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='addresses',
                    unique_together={('street', 'number', 'neighborhood', 'city', 'state', 'zip_code')},
                ),
                migrations.AlterUniqueTogether(
                    name='states',
                    unique_together={('name', 'abbreviation')},
                ),
                migrations.AlterUniqueTogether(
                    name='structioncondominium',
                    unique_together={('name',)},
                ),
                migrations.AlterUniqueTogether(
                    name='typescondominium',
                    unique_together={('name',)},
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterUniqueTogether(
            name='condominium',
            unique_together={('cnpj',), ('code',)},
        ),
    ]
