# Generated by Django 5.0.3 on 2026-04-12 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0009_alter_addresses_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=20, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='condominium.condominium', verbose_name='Condomínio')),
            ],
            options={
                'verbose_name': '6. Colaborador',
                'verbose_name_plural': '6. Colaboradores',
                'ordering': ['name', 'email', 'phone_number', 'created_at'],
                'unique_together': {('condominium', 'cpf'), ('name', 'cpf')},
            },
        ),
    ]
