# Generated by Django 5.0.3 on 2026-04-13 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0011_collaborators_observations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborators',
            options={'ordering': ['name', 'email', 'phone_number', 'created_at'], 'verbose_name': '7. Colaborador', 'verbose_name_plural': '7. Colaboradores'},
        ),
        migrations.CreateModel(
            name='Types_collaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tipo de Colaborador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '6. Tipo de Colaborador',
                'verbose_name_plural': '6. Tipos de Colaboradores',
                'ordering': ['name', 'is_active', 'created_at'],
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='collaborators',
            name='type_collaborator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Types_collaborators', to='condominium.types_collaborators', verbose_name='Tipo de Colaborador'),
        ),
    ]
