# Generated by Django 5.0.3 on 2026-04-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0013_alter_addresses_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='number',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
    ]
