# Generated by Django 5.0.3 on 2026-04-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0014_alter_addresses_number'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='addresses',
                    name='number',
                    field=models.CharField(max_length=10, verbose_name='Número'),
                ),
            ],
            database_operations=[],
        ),
    ]
