# Generated by Django 5.0.3 on 2026-04-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0019_alter_addresses_number'),
    ]

    operations = [
    ]
