# Generated by Django 5.0.3 on 2026-04-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0021_auto_20260418_0703'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='addresses',
                    name='number',
                    field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Número'),
                ),
            ],
            database_operations=[],
        ),
    ]
