# Generated by Django 5.0.3 on 2026-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0024_alter_addresses_number'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='addresses',
                    name='number',
                    field=models.IntegerField(verbose_name='Número'),
                ),
            ],
            database_operations=[],
        ),
    ]
