# Generated by Django 5.0.3 on 2026-05-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0025_alter_addresses_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='condominium',
            unique_together=set(),
        ),
    ]
