# Generated by Django 5.0.3 on 2026-05-05 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0026_alter_condominium_unique_together'),
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='addresses',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='addresses',
                    name='state',
                ),
                migrations.AlterUniqueTogether(
                    name='structioncondominium',
                    unique_together=None,
                ),
                migrations.AlterUniqueTogether(
                    name='typescondominium',
                    unique_together=None,
                ),
                migrations.DeleteModel(
                    name='States',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='condominium',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium', to='parameters.addresses', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='struction_condominium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condominium', to='parameters.structioncondominium', verbose_name='Estrutura do Condomínio'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='type_condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium', to='parameters.typescondominium', verbose_name='Tipo de Condomínio'),
        ),
    ]
