# Generated by Django 5.0.3 on 2026-05-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0027_alter_addresses_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='Addresses'),
                migrations.DeleteModel(name='StructionCondominium'),
                migrations.DeleteModel(name='TypesCondominium'),
            ],
            database_operations=[],
        ),
        migrations.AlterModelOptions(
            name='collaborators',
            options={'ordering': ['name', 'email', 'phone_number', 'created_at'], 'verbose_name': '3. Colaborador', 'verbose_name_plural': '3. Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='condominium',
            options={'ordering': ['name', 'code', 'cnpj', 'is_active', 'created_at'], 'verbose_name': '1. Condomínio', 'verbose_name_plural': '1. Condomínios'},
        ),
        migrations.AlterModelOptions(
            name='types_collaborators',
            options={'ordering': ['name', 'is_active', 'created_at'], 'verbose_name': '2. Tipo de Colaborador', 'verbose_name_plural': '2. Tipos de Colaboradores'},
        ),
    ]
