# Generated by Django 5.0.3 on 2026-05-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0028_delete_addresses_delete_structioncondominium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='condominium/collaborators/', verbose_name='Foto'),
        ),
    ]
