# Generated by Django 5.0.3 on 2026-05-12 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0029_collaborators_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCondominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Documento')),
                ('file', models.FileField(upload_to='condominium/documents/', verbose_name='Arquivo do Documento')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='condominium.condominium', verbose_name='Condomínio')),
            ],
            options={
                'verbose_name': '4. Documento do Condomínio',
                'verbose_name_plural': '4. Documentos do Condomínio',
                'ordering': ['name', 'created_at'],
            },
        ),
    ]
