# Generated by Django 5.0.3 on 2026-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0032_collaborators_api_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='retorno_api',
            field=models.TextField(blank=True, null=True, verbose_name='Retorno da API'),
        ),
    ]
