# Generated by Django 5.0.3 on 2026-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0034_collaborators_date_time_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certidoes/', verbose_name='Arquivo da certidão'),
        ),
        migrations.AddField(
            model_name='collaborators',
            name='certificate_presentation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de apresentação da certidão'),
        ),
        migrations.AddField(
            model_name='collaborators',
            name='certificate_validity',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da certidão'),
        ),
        migrations.AddField(
            model_name='collaborators',
            name='observations_certificate',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
