# Generated by Django 5.0.3 on 2026-05-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0035_collaborators_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborators',
            options={'ordering': ['name', 'email', 'phone_number', 'created_at'], 'verbose_name': '03. Colaborador', 'verbose_name_plural': '03. Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='condominium',
            options={'ordering': ['name', 'code', 'cnpj', 'is_active', 'created_at'], 'verbose_name': '01. Condomínio', 'verbose_name_plural': '01. Condomínios'},
        ),
        migrations.AlterModelOptions(
            name='types_collaborators',
            options={'ordering': ['name', 'is_active', 'created_at'], 'verbose_name': '02. Tipo de Colaborador', 'verbose_name_plural': '02. Tipos de Colaboradores'},
        ),
    ]
