# Generated by Django 5.0.3 on 2026-06-14 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0036_alter_collaborators_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='types_collaborators',
            unique_together=None,
        ),
        migrations.AlterModelTable(
            name='condominium',
            table='condominium_condominium',
        ),
        migrations.CreateModel(
            name='TypesCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tipo de Colaborador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '02. Tipo de Colaborador',
                'verbose_name_plural': '02. Tipos de Colaboradores',
                'db_table': 'condominium_types_collaborators',
                'ordering': ['name', 'is_active', 'created_at'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=20, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='condominium/collaborators/', verbose_name='Foto')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('situation', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Suspenso', 'Suspenso'), ('Pendente de Regularização', 'Pendente de Regularização'), ('Cancelado', 'Cancelado'), ('Titular Falecido', 'Titular Falecido'), ('Nulo', 'Nulo')], max_length=100, null=True, verbose_name='Situação Receita Federal')),
                ('regular', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='CPF Regular')),
                ('death', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Óbito')),
                ('api_status', models.CharField(blank=True, default='nulo', editable=False, max_length=100, null=True, verbose_name='Status da API')),
                ('retorno_api', models.TextField(blank=True, default='nulo', editable=False, null=True, verbose_name='Retorno da API')),
                ('date_time_appointment', models.DateTimeField(auto_now=True, null=True, verbose_name='Data/hora da consulta')),
                ('certificate_presentation_date', models.DateField(blank=True, null=True, verbose_name='Data de apresentação da certidão')),
                ('certificate_validity', models.DateField(blank=True, null=True, verbose_name='Validade da certidão')),
                ('observations_certificate', models.TextField(blank=True, null=True, verbose_name='Observações da certidão')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certidoes/', verbose_name='Arquivo da certidão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='condominium.condominium', verbose_name='Condomínio')),
                ('type_collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Types_collaborators', to='condominium.typescollaborator', verbose_name='Tipo de Colaborador')),
            ],
            options={
                'verbose_name': '03. Colaborador',
                'verbose_name_plural': '03. Colaboradores',
                'db_table': 'condominium_collaborators',
                'ordering': ['name', 'email', 'phone_number', 'created_at'],
                'unique_together': {('condominium', 'cpf'), ('name', 'cpf')},
            },
        ),
        migrations.DeleteModel(
            name='Collaborators',
        ),
        migrations.DeleteModel(
            name='Types_collaborators',
        ),
    ]
