# Generated by Django 5.0.3 on 2026-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0037_alter_types_collaborators_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nome'),
        ),
    ]
