# Generated by Django 5.0.3 on 2026-05-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0003_virtualassembly'),
        ('condominium', '0036_alter_collaborators_options_and_more'),
        ('parameters', '0005_alter_addresses_options_alter_states_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': '1. Banco', 'verbose_name_plural': '1. Bancos'},
        ),
        migrations.AlterModelOptions(
            name='budgetforecast',
            options={'verbose_name': '8. Previsão Orçamentária', 'verbose_name_plural': '8. Previsões Orçamentárias'},
        ),
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'verbose_name': '9. Plano de Conta', 'verbose_name_plural': '9. Plano de Contas'},
        ),
        migrations.AlterModelOptions(
            name='circular',
            options={'verbose_name': '2. Circular', 'verbose_name_plural': '2. Circulares'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '3. Contrato', 'verbose_name_plural': '3. Contratos'},
        ),
        migrations.AlterModelOptions(
            name='infraction',
            options={'verbose_name': '4. Infração', 'verbose_name_plural': '4. Infrações'},
        ),
        migrations.AlterModelOptions(
            name='meter',
            options={'verbose_name': '5. Medidor', 'verbose_name_plural': '5. Medidores'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '6. Notificação', 'verbose_name_plural': '6. Notificações'},
        ),
        migrations.AlterModelOptions(
            name='patrimony',
            options={'verbose_name': '7. Patrimônio', 'verbose_name_plural': '7. Patrimônios'},
        ),
        migrations.AddField(
            model_name='bank',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Conta'),
        ),
        migrations.AddField(
            model_name='bank',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Conta'),
        ),
        migrations.AddField(
            model_name='bank',
            name='account_type',
            field=models.CharField(blank=True, choices=[('checking_account', 'Conta Corrente'), ('savings_account', 'Conta Poupança'), ('university_account', 'Conta Universitária'), ('digital_account', 'Conta Digital'), ('salary_account', 'Conta-Salário'), ('joint_account', 'Conta Conjunta'), ('business_account', 'Conta Empresarial'), ('international_account', 'Conta Internacional'), ('investment_account', 'Conta Investimento')], max_length=50, null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='bank',
            name='addresses_drawn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawn_address', to='parameters.addresses', verbose_name='Endereço Sacado'),
        ),
        migrations.AddField(
            model_name='bank',
            name='agency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank', to='parameters.addresses', verbose_name='Endereço do Banco'),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Banco'),
        ),
        migrations.AddField(
            model_name='bank',
            name='compe',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='COMPE - Código Banco'),
        ),
        migrations.AddField(
            model_name='bank',
            name='condominium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank', to='condominium.condominium', verbose_name='Condomínio Beneficiário'),
        ),
        migrations.AddField(
            model_name='bank',
            name='cpf_drawn',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF Sacado'),
        ),
        migrations.AddField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='bank',
            name='email_drawn',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Sacado'),
        ),
        migrations.AddField(
            model_name='bank',
            name='email_manager',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Gerente'),
        ),
        migrations.AddField(
            model_name='bank',
            name='full_name_drawn',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Completo Sacado'),
        ),
        migrations.AddField(
            model_name='bank',
            name='full_name_manager',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome do Gerente'),
        ),
        migrations.AddField(
            model_name='bank',
            name='iban',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='bank',
            name='initial_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Saldo Inicial'),
        ),
        migrations.AddField(
            model_name='bank',
            name='initial_balance_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Saldo Inicial'),
        ),
        migrations.AddField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='bank',
            name='phone1_manager',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1 Gerente'),
        ),
        migrations.AddField(
            model_name='bank',
            name='phone2_manager',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2 Gerente'),
        ),
        migrations.AddField(
            model_name='bank',
            name='phone3_manager',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 3 Gerente'),
        ),
        migrations.AddField(
            model_name='bank',
            name='phone_drawn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Sacado'),
        ),
        migrations.AddField(
            model_name='bank',
            name='rg_drawn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG Sacado'),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('compe', 'account_type', 'agency', 'account_number'), ('compe', 'agency', 'account_number', 'cpf_drawn')},
        ),
    ]
