# Generated by Django 5.0.3 on 2026-05-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0005_alter_bank_compe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='compe',
            field=models.PositiveIntegerField(blank=True, max_length=5, null=True, verbose_name='Cod. Banco'),
        ),
    ]
