# Generated by Django 5.0.3 on 2026-05-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0006_alter_bank_compe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='initial_balance_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data Saldo Inicial'),
        ),
    ]
