# Generated by Django 5.0.3 on 2026-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0007_alter_bank_initial_balance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='initial_balance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Saldo Inicial'),
        ),
    ]
