# Generated by Django 5.0.3 on 2026-05-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0009_bank_account_digit_alter_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_digit',
            field=models.CharField(max_length=2, verbose_name='Dígito da Conta'),
        ),
    ]
